"""Module-level helpers the WordPress tools call.

Generated by scripts/audit_wordpress_tools.py alongside the tool modules.
Kept in one place because helpers are shared across families -- Elementor
widget builders are used by builders.py and core.py alike.
"""
from __future__ import annotations

import base64 as base64_lib  # noqa: F401
import json  # noqa: F401
import mimetypes  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
from datetime import date, timedelta  # noqa: F401
from typing import Any, List, Optional  # noqa: F401
from urllib.parse import quote, urlparse  # noqa: F401

import requests  # noqa: F401

from .client import _trim, _unsupported_from_http, _wp  # noqa: F401

__all__ = ['_WP_BLOCK_TOKEN_RE', '_allowed_hosts', '_allowed_origins', '_elementor_append_widget_to_section', '_elementor_build_widget_settings', '_elementor_clone_with_new_ids', '_elementor_collect_widgets', '_elementor_content_collection', '_elementor_count_widgets', '_elementor_create_library_template', '_elementor_decode_meta_json', '_elementor_encode_json_blob', '_elementor_find_element', '_elementor_flatten_items', '_elementor_format_document', '_elementor_get_document', '_elementor_get_document_structure', '_elementor_get_library_document', '_elementor_insert_elements', '_elementor_insert_widget', '_elementor_is_native_structure', '_elementor_make_column', '_elementor_make_container', '_elementor_make_heading_section', '_elementor_make_section', '_elementor_make_widget', '_elementor_match_plugin', '_elementor_merge_element_settings', '_elementor_new_element_id', '_elementor_normalize_structure', '_elementor_resolve_insert_index', '_elementor_schema_required', '_elementor_section_type_key', '_elementor_target_children', '_elementor_update_document_structure', '_elementor_upsert_widget', '_elementor_validate_data_json', '_elementor_validate_native_elements', '_server_base_url', '_wp_apply_block_operations', '_wp_block_index', '_wp_get_editable_content', '_wp_global_styles_resolution_hint', '_wp_parse_block_markup', '_wp_parse_blocks_content', '_wp_render_block_markup', '_wp_save_blocks', '_wp_serialize_blocks', '_wp_split_top_level_blocks']


_server_base_url = os.environ.get("SERVER_BASE_URL", "").rstrip("/")


_allowed_hosts = ["127.0.0.1:*", "localhost:*", "[::1]:*"]


_allowed_origins = [
    "http://127.0.0.1:*",
    "http://localhost:*",
    "http://[::1]:*",
]


def _elementor_content_collection(content_type: str) -> str:
    normalized = (content_type or "page").strip().lower()
    if normalized in {"page", "pages"}:
        return "pages"
    if normalized in {"post", "posts"}:
        return "posts"
    return normalized


def _elementor_decode_meta_json(value: Any) -> Any:
    if not isinstance(value, str):
        return value
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        return value


def _elementor_encode_json_blob(value: Any, field_name: str) -> str:
    if isinstance(value, (dict, list)):
        return json.dumps(value)
    if not isinstance(value, str):
        raise ValueError(f"{field_name} must be a JSON string, list, or dict")
    try:
        json.loads(value)
    except json.JSONDecodeError as exc:
        raise ValueError(f"{field_name} must be valid JSON") from exc
    return value


def _elementor_is_native_structure(value: Any) -> bool:
    if not isinstance(value, list):
        return False
    supported_types = {"section", "column", "container", "widget"}
    for element in value:
        if not isinstance(element, dict):
            return False
        if element.get("elType") not in supported_types:
            return False
        if not isinstance(element.get("id"), str) or not element.get("id"):
            return False
        if element.get("elType") == "widget" and (not isinstance(element.get("widgetType"), str) or not element.get("widgetType")):
            return False
    return True


def _elementor_validate_native_elements(elements: Any) -> None:
    if not isinstance(elements, list):
        raise ValueError("elementor_data must be a JSON array of native Elementor elements")
    supported_types = {"section", "column", "container", "widget"}
    for element in elements:
        if not isinstance(element, dict):
            raise ValueError("Each Elementor element must be an object")
        el_type = element.get("elType")
        if el_type not in supported_types:
            raise ValueError(
                "elementor_data must use native Elementor element objects with elType values like section, column, container, or widget. "
                "Use elementor_build_page or elementor_preset_* for descriptive section briefs."
            )
        if not isinstance(element.get("id"), str) or not element.get("id"):
            raise ValueError("Each Elementor element must include a non-empty string id")
        if el_type == "widget" and (not isinstance(element.get("widgetType"), str) or not element.get("widgetType")):
            raise ValueError("Each Elementor widget element must include a non-empty widgetType")
        children = element.get("elements") or []
        if not isinstance(children, list):
            raise ValueError("Each Elementor element must store child elements in a list")
        _elementor_validate_native_elements(children)


def _elementor_validate_data_json(elementor_data: Any) -> str:
    encoded = _elementor_encode_json_blob(elementor_data, "elementor_data")
    parsed = json.loads(encoded)
    _elementor_validate_native_elements(parsed)
    return encoded


def _elementor_get_document(post_id: int, content_type: str) -> dict:
    collection = _elementor_content_collection(content_type)
    return _wp().get(f"/wp/v2/{collection}/{post_id}", params={"context": "edit"})


def _elementor_get_library_document(template_id: int) -> dict:
    return _wp().get(f"/wp/v2/elementor_library/{template_id}", params={"context": "edit"})


def _elementor_schema_required(feature: str, reason: str, alternatives: list[str] | None = None, **details: Any) -> dict:
    payload = {
        "supported": False,
        "feature": feature,
        "reason": reason,
    }
    if alternatives:
        payload["alternatives"] = alternatives
    payload.update(details)
    return payload


def _elementor_create_library_template(
    title: str,
    template_type: str = "page",
    content: Any = None,
    page_settings: dict | None = None,
    status: str = "publish",
) -> dict:
    body = {"title": title, "status": status}
    if template_type is not None:
        body["type"] = template_type
    created = _wp().post("/wp/v2/elementor_library", json=body)
    if content is None and page_settings is None:
        template = _elementor_format_document(_elementor_get_library_document(created["id"]))
    else:
        template = elementor_update_page_data(
            created["id"],
            content if content is not None else [],
            type="elementor_library",
            page_settings=page_settings,
        )
    template["template_kind"] = template_type
    return template


def _elementor_format_document(document: dict) -> dict:
    meta = document.get("meta") or {}
    return {
        "id": document.get("id"),
        "type": document.get("type"),
        "status": document.get("status"),
        "slug": document.get("slug"),
        "title": document.get("title"),
        "template": document.get("template"),
        "edit_mode": meta.get("_elementor_edit_mode"),
        "elementor_enabled": meta.get("_elementor_edit_mode") == "builder",
        "elementor_data": _elementor_decode_meta_json(meta.get("_elementor_data")),
        "page_settings": _elementor_decode_meta_json(meta.get("_elementor_page_settings")),
        "meta": meta,
    }


def _elementor_new_element_id() -> str:
    return os.urandom(4).hex()


def _elementor_normalize_structure(structure: Any) -> list:
    if isinstance(structure, list):
        return structure
    return []


def _elementor_make_column(size: int | None = None) -> dict:
    settings: dict[str, Any] = {}
    if size is not None:
        settings["_column_size"] = size
    return {
        "id": _elementor_new_element_id(),
        "elType": "column",
        "isInner": False,
        "settings": settings,
        "elements": [],
    }


def _elementor_make_section(columns: int = 1, settings: dict | None = None) -> dict:
    column_count = max(1, int(columns or 1))
    column_size = max(1, int(100 / column_count))
    return {
        "id": _elementor_new_element_id(),
        "elType": "section",
        "isInner": False,
        "settings": settings or {},
        "elements": [_elementor_make_column(column_size) for _ in range(column_count)],
    }


def _elementor_make_container(settings: dict | None = None) -> dict:
    return {
        "id": _elementor_new_element_id(),
        "elType": "container",
        "isInner": False,
        "settings": settings or {},
        "elements": [],
    }


def _elementor_make_widget(widget_type: str, settings: dict | None = None) -> dict:
    return {
        "id": _elementor_new_element_id(),
        "elType": "widget",
        "widgetType": widget_type,
        "settings": settings or {},
        "elements": [],
    }


def _elementor_append_widget_to_section(section: dict, widget_type: str, settings: dict | None = None, column_index: int = 0) -> dict:
    columns = section.setdefault("elements", [])
    if not columns:
        columns.append(_elementor_make_column())
    slot = max(0, min(column_index, len(columns) - 1))
    widget = _elementor_make_widget(widget_type, _elementor_build_widget_settings(widget_type, settings))
    columns[slot].setdefault("elements", []).append(widget)
    return widget


def _elementor_resolve_insert_index(position: Any, length: int) -> int:
    if position in (None, "last"):
        return length
    if position == "first":
        return 0
    if isinstance(position, str) and position.isdigit():
        position = int(position)
    if isinstance(position, int):
        return max(0, min(position, length))
    return length


def _elementor_insert_elements(page_id: int, page_type: str, elements: list, position: Any = "end") -> dict:
    items = [element for element in list(elements or []) if element is not None]
    if not items:
        return {
            "page": elementor_get_page_data(page_id, page_type),
            "section_ids": [],
            "applied_to_page": True,
        }
    _, structure = _elementor_get_document_structure(page_id, page_type)
    insert_at = _elementor_resolve_insert_index(position, len(structure))
    element_ids: list[str] = []
    for offset, element in enumerate(items):
        structure.insert(insert_at + offset, element)
        if isinstance(element, dict) and isinstance(element.get("id"), str):
            element_ids.append(element["id"])
    updated = _elementor_update_document_structure(page_id, page_type, structure)
    return {
        "page": updated,
        "section_ids": element_ids,
        "applied_to_page": True,
    }


def _elementor_make_heading_section(
    title: str,
    subtitle: str | None = None,
    bg_color: str | None = None,
    text_color: str | None = None,
    padding_top: str = "70",
    padding_bottom: str = "20",
) -> dict:
    settings = {"padding": {"top": padding_top, "bottom": padding_bottom}}
    if bg_color is not None:
        settings["background_color"] = bg_color
    section = _elementor_make_section(columns=1, settings=settings)
    heading_settings = {"text": title, "tag": "h2", "align": "center"}
    if text_color is not None:
        heading_settings["color"] = text_color
    _elementor_append_widget_to_section(section, "heading", heading_settings)
    if subtitle is not None:
        subtitle_settings = {"content": subtitle, "align": "center"}
        if text_color is not None:
            subtitle_settings["text_color"] = text_color
        _elementor_append_widget_to_section(section, "text-editor", subtitle_settings)
    return section


def _elementor_section_type_key(section_type: Any) -> str:
    return str(section_type or "").strip().lower().replace("_", "-").replace(" ", "-")


def _elementor_find_element(elements: list, element_id: str) -> dict | None:
    for index, element in enumerate(elements):
        if str(element.get("id")) == str(element_id):
            return {"element": element, "siblings": elements, "index": index}
        found = _elementor_find_element(element.get("elements") or [], element_id)
        if found:
            return found
    return None


def _elementor_target_children(structure: list, section_index: int = 0, column_index: int = 0) -> list:
    if not structure:
        structure.append(_elementor_make_section())
    root_index = max(0, min(section_index, len(structure) - 1))
    root_element = structure[root_index]
    root_type = root_element.get("elType")
    if root_type in {"container", "column"}:
        return root_element.setdefault("elements", [])
    if root_type == "section":
        columns = root_element.setdefault("elements", [])
        if not columns:
            columns.append(_elementor_make_column())
        column_slot = max(0, min(column_index, len(columns) - 1))
        return columns[column_slot].setdefault("elements", [])
    return root_element.setdefault("elements", [])


def _elementor_clone_with_new_ids(element: dict) -> dict:
    cloned = json.loads(json.dumps(element))
    def _reassign_ids(node: dict) -> None:
        node["id"] = _elementor_new_element_id()
        for child in node.get("elements") or []:
            _reassign_ids(child)
    _reassign_ids(cloned)
    return cloned


def _elementor_collect_widgets(elements: list, widgets: list | None = None) -> list:
    if widgets is None:
        widgets = []
    for element in elements:
        if element.get("elType") == "widget":
            widgets.append({
                "id": element.get("id"),
                "widgetType": element.get("widgetType"),
                "settings": element.get("settings") or {},
            })
        _elementor_collect_widgets(element.get("elements") or [], widgets)
    return widgets


def _elementor_merge_element_settings(page_id: int, page_type: str, element_id: str, settings: dict, allowed_types: set[str] | None = None) -> dict:
    _, structure = _elementor_get_document_structure(page_id, page_type)
    found = _elementor_find_element(structure, element_id)
    if not found:
        raise ValueError(f"Element '{element_id}' not found")
    element_type = found["element"].get("elType")
    if allowed_types is not None and element_type not in allowed_types:
        raise ValueError(f"Element '{element_id}' is not one of: {', '.join(sorted(allowed_types))}")
    found["element"]["settings"] = {**(found["element"].get("settings") or {}), **(settings or {})}
    return _elementor_update_document_structure(page_id, page_type, structure)


def _elementor_update_document_structure(page_id: int, page_type: str, structure: list) -> dict:
    collection = _elementor_content_collection(page_type)
    updated = _wp().post(
        f"/wp/v2/{collection}/{page_id}",
        json={
            "meta": {
                "_elementor_data": _elementor_validate_data_json(structure),
                "_elementor_edit_mode": "builder",
            }
        },
    )
    return _elementor_format_document(updated)


def _elementor_get_document_structure(page_id: int, page_type: str) -> tuple[dict, list]:
    document = _elementor_format_document(_elementor_get_document(page_id, page_type))
    structure = _elementor_normalize_structure(document.get("elementor_data"))
    return document, structure


def _elementor_build_widget_settings(widget_type: str, raw_settings: dict | None) -> dict:
    settings = dict(raw_settings or {})
    if widget_type in {"heading", "text-editor", "button", "image", "icon"}:
        settings.setdefault("_widget_type", widget_type)
    return settings


def _elementor_flatten_items(result: Any) -> list:
    if isinstance(result, dict) and isinstance(result.get("data"), list):
        return result["data"]
    if isinstance(result, list):
        return result
    return []


def _elementor_match_plugin(plugins: list, plugin_file: str) -> dict | None:
    target = plugin_file.lower()
    for plugin in plugins:
        plugin_id = str(plugin.get("plugin") or plugin.get("slug") or plugin.get("textdomain") or "").lower()
        if plugin_id == target or plugin_id.endswith(target):
            return plugin
    return None


def _elementor_count_widgets(elements: Any) -> int:
    if not isinstance(elements, list):
        return 0
    total = 0
    for element in elements:
        if not isinstance(element, dict):
            continue
        if element.get("elType") == "widget":
            total += 1
        total += _elementor_count_widgets(element.get("elements") or [])
    return total


_WP_BLOCK_TOKEN_RE = re.compile(r"<!--\s*(/)?wp:([^\s/]+)(?:\s+(\{.*?\}))?\s*(/)?-->", re.S)


def _wp_split_top_level_blocks(content: str) -> list[str]:
    source = content or ""
    blocks: list[str] = []
    depth = 0
    cursor = 0
    current_start: int | None = None
    for match in _WP_BLOCK_TOKEN_RE.finditer(source):
        is_close = bool(match.group(1))
        is_self_closing = bool(match.group(4))
        if depth == 0 and match.start() > cursor:
            raw_chunk = source[cursor:match.start()]
            if raw_chunk.strip():
                blocks.append(raw_chunk.strip())
                cursor = match.start()
        if not is_close:
            if is_self_closing:
                if depth == 0:
                    blocks.append(source[match.start():match.end()].strip())
                    cursor = match.end()
                continue
            if depth == 0:
                current_start = match.start()
            depth += 1
            continue
        if depth > 0:
            depth -= 1
            if depth == 0 and current_start is not None:
                blocks.append(source[current_start:match.end()].strip())
                cursor = match.end()
                current_start = None
    if cursor < len(source):
        tail = source[cursor:]
        if tail.strip():
            blocks.append(tail.strip())
    return blocks


def _wp_parse_block_markup(block_markup: str) -> dict:
    markup = (block_markup or "").strip()
    if not markup:
        return {"blockName": None, "attrs": {}, "innerHTML": "", "originalContent": "", "raw": True}
    match = _WP_BLOCK_TOKEN_RE.match(markup)
    if not match or match.group(1):
        return {"blockName": None, "attrs": {}, "innerHTML": markup, "originalContent": markup, "raw": True}
    block_name = match.group(2)
    attrs_blob = match.group(3)
    attrs = json.loads(attrs_blob) if attrs_blob else {}
    if match.group(4):
        return {"blockName": block_name, "attrs": attrs, "innerHTML": "", "originalContent": markup}
    closing_token = f"<!-- /wp:{block_name} -->"
    inner_html = markup[match.end():]
    if inner_html.endswith(closing_token):
        inner_html = inner_html[:-len(closing_token)]
    return {
        "blockName": block_name,
        "attrs": attrs,
        "innerHTML": inner_html.strip(),
        "originalContent": markup,
    }


def _wp_render_block_markup(block: dict) -> str:
    if not isinstance(block, dict):
        return str(block or "").strip()
    block_name = block.get("blockName") or block.get("name")
    if not block_name:
        return str(block.get("originalContent") or block.get("innerHTML") or block.get("content") or "").strip()
    attrs = block.get("attrs") or {}
    attrs_blob = f" {json.dumps(attrs, separators=(',', ':'))}" if attrs else ""
    inner_html = block.get("innerHTML")
    if inner_html is None and isinstance(block.get("innerBlocks"), list):
        inner_html = _wp_serialize_blocks(block.get("innerBlocks") or [])
    inner_html = str(inner_html or "")
    return f"<!-- wp:{block_name}{attrs_blob} -->{inner_html}<!-- /wp:{block_name} -->"


def _wp_parse_blocks_content(content: str) -> list[dict]:
    return [_wp_parse_block_markup(block) for block in _wp_split_top_level_blocks(content)]


def _wp_serialize_blocks(blocks: list) -> str:
    return "\n\n".join(_wp_render_block_markup(block) for block in (blocks or []) if str(_wp_render_block_markup(block)).strip()).strip()


def _wp_get_editable_content(post_id: int, post_type: str) -> tuple[str, dict]:
    collection = _elementor_content_collection(post_type)
    document = _wp().get(f"/wp/v2/{collection}/{post_id}", params={"context": "edit"})
    content = document.get("content")
    raw_content = content.get("raw") if isinstance(content, dict) else content or ""
    return raw_content or "", document


def _wp_save_blocks(post_id: int, post_type: str, blocks: list) -> dict:
    collection = _elementor_content_collection(post_type)
    content = _wp_serialize_blocks(blocks)
    updated = _wp().post(f"/wp/v2/{collection}/{post_id}", json={"content": content})
    return {
        "post_id": post_id,
        "post_type": collection,
        "content": content,
        "blocks": _wp_parse_blocks_content(content),
        "post": updated,
    }


def _wp_block_index(index: int, blocks: list) -> int:
    if index < 0 or index >= len(blocks):
        raise IndexError(f"Block index {index} is out of range")
    return index


def _wp_apply_block_operations(blocks: list, operations: list) -> list:
    working = list(blocks)
    for operation in operations or []:
        action = str((operation or {}).get("op") or (operation or {}).get("action") or "").strip().lower()
        if action == "insert":
            insert_at = int((operation or {}).get("position", len(working)))
            insert_at = max(0, min(insert_at, len(working)))
            working.insert(insert_at, operation.get("block") or {})
        elif action == "update":
            index = _wp_block_index(int(operation.get("index")), working)
            current = dict(working[index] or {})
            current["attrs"] = {**(current.get("attrs") or {}), **(operation.get("attrs") or {})}
            if "innerHTML" in operation:
                current["innerHTML"] = operation.get("innerHTML")
            working[index] = current
        elif action == "remove":
            working.pop(_wp_block_index(int(operation.get("index")), working))
        elif action == "move":
            from_index = _wp_block_index(int(operation.get("from_index")), working)
            block = working.pop(from_index)
            to_index = max(0, min(int(operation.get("to_index", len(working))), len(working)))
            working.insert(to_index, block)
        elif action == "replace":
            working[_wp_block_index(int(operation.get("index")), working)] = operation.get("block") or {}
        elif action == "wrap":
            start_index = _wp_block_index(int(operation.get("start_index")), working)
            end_index = _wp_block_index(int(operation.get("end_index")), working)
            if end_index < start_index:
                raise ValueError("end_index must be >= start_index")
            wrapper_name = operation.get("wrapper") or "group"
            wrapper_attrs = operation.get("wrapper_attrs") or {}
            wrapped_blocks = working[start_index:end_index + 1]
            wrapper_block = {
                "blockName": wrapper_name,
                "attrs": wrapper_attrs,
                "innerHTML": _wp_serialize_blocks(wrapped_blocks),
            }
            working[start_index:end_index + 1] = [wrapper_block]
        else:
            raise ValueError(f"Unsupported block batch operation '{action}'")
    return working


def _wp_global_styles_resolution_hint() -> dict:
    try:
        active_theme = _wp().get("/wp/v2/themes", params={"status": "active"})
    except requests.HTTPError as exc:
        active_theme = _unsupported_from_http(exc, "wp/v2 themes controller")
    return {
        "supported": False,
        "reason": "Global styles operations without a concrete global styles id are ambiguous. Use the explicit id-based global styles tools with a verified id from the site.",
        "active_theme": active_theme,
    }


def _elementor_insert_widget(
    page_id: int,
    page_type: str,
    widget_type: str,
    section_index: int = 0,
    column_index: int = 0,
    settings: dict | None = None,
) -> dict:
    _, structure = _elementor_get_document_structure(page_id, page_type)
    target_children = _elementor_target_children(structure, section_index, column_index)
    target_children.append(_elementor_make_widget(widget_type, _elementor_build_widget_settings(widget_type, settings)))
    return _elementor_update_document_structure(page_id, page_type, structure)


def _elementor_upsert_widget(
    page_id: int,
    page_type: str,
    widget_type: str,
    settings: dict | None = None,
    section_index: int = 0,
    column_index: int = 0,
    element_id: str | None = None,
) -> dict:
    if element_id is not None:
        return elementor_update_widget_settings(page_id, element_id, settings or {}, page_type=page_type)
    return _elementor_insert_widget(page_id, page_type, widget_type, section_index, column_index, settings)
