"""WordPress analytics tools -- generated by scripts/audit_wordpress_tools.py.

Do not edit by hand; re-run the script instead. Tools that failed the audit
are still emitted but listed in tool_registry._BROKEN_WORDPRESS_ACTIONS so
they are hidden from discovery.
"""
from __future__ import annotations

import base64 as base64_lib  # noqa: F401
import json  # noqa: F401
import mimetypes  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
from datetime import date, timedelta  # noqa: F401
from typing import Any, List, Optional  # noqa: F401
from urllib.parse import quote, urlparse  # noqa: F401

import requests  # noqa: F401

from mcp_instance import mcp
from permissions import require_editor  # noqa: F401

from .client import _trim, _unsupported_from_http, _wp  # noqa: F401
from ._helpers import *  # noqa: F401,F403 -- shared private helpers


@mcp.tool()
def analytics_detect_plugin() -> dict:
    """Detect which analytics plugin is active: MonsterInsights, Site Kit, Analytify, ExactMetrics, or none"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_gtm_install(
    container_id: str,
    method: str = "plugin_settings",
) -> dict:
    """Install Google Tag Manager container code via companion plugin settings or custom code injection"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_gtm_get_container_id() -> dict:
    """Get the currently configured GTM container ID from plugin settings or site options"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_ga4_configure(
    measurement_id: str,
    plugin: str = "auto",
) -> dict:
    """Set GA4 measurement ID via MonsterInsights, Site Kit, ExactMetrics, or companion settings"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_ga4_test_event(
    measurement_id: str,
    api_secret: str,
    event_name: str = "test_event",
    params: dict = None,
) -> dict:
    """Send a test event to GA4 via Measurement Protocol. Returns the payload and endpoint to use for server-side tracking"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_meta_pixel_install(
    pixel_id: str,
    method: str = "plugin_settings",
) -> dict:
    """Install Meta/Facebook pixel tracking code on the site via plugin settings or code injection"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_meta_pixel_configure(
    pixel_id: str,
    advanced_matching: bool = None,
    track_pageview: bool = True,
    track_viewcontent: bool = None,
    track_addtocart: bool = None,
    track_purchase: bool = None,
) -> dict:
    """Configure Meta Pixel settings (events, advanced matching, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_meta_capi_send(
    pixel_id: str,
    access_token: str,
    event_name: str,
    event_data: dict = None,
    user_data: dict = None,
) -> dict:
    """Send a server-side event via Meta Conversions API. Returns the payload and endpoint format for server-side event tracking"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_tiktok_pixel_install(
    pixel_id: str,
) -> dict:
    """Install TikTok pixel tracking code on the site"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_linkedin_insight_install(
    partner_id: str,
) -> dict:
    """Install LinkedIn Insight Tag on the site for conversion tracking and audience building"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_twitter_pixel_install(
    pixel_id: str,
) -> dict:
    """Install Twitter/X pixel for conversion tracking"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_pinterest_tag_install(
    tag_id: str,
) -> dict:
    """Install Pinterest Tag for conversion tracking"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_clarity_install(
    project_id: str,
) -> dict:
    """Install Microsoft Clarity session recording and heatmap tracking code"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_hotjar_install(
    site_id: str,
) -> dict:
    """Install Hotjar heatmap and session recording tracking code"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_utm_builder(
    url: str,
    utm_source: str,
    utm_medium: str,
    utm_campaign: str,
    utm_term: str = None,
    utm_content: str = None,
) -> dict:
    """Generate a URL with UTM tracking parameters for campaign tracking"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_wc_enhanced_ecommerce(
    measurement_id: str,
    plugin: str = "auto",
    track_product_views: bool = True,
    track_add_to_cart: bool = True,
    track_checkout: bool = True,
    track_purchases: bool = True,
) -> dict:
    """Configure WooCommerce Enhanced Ecommerce tracking for GA4 (product impressions, add to cart, checkout, purchase events)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_custom_event_inject(
    code: str,
    location: str = "footer",
    label: str = None,
) -> dict:
    """Inject custom JavaScript event tracking code into wp_head or wp_footer via companion plugin or custom code option"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_consent_banner_detect() -> dict:
    """Detect which cookie consent plugin is active (CookieYes, Complianz, CookieBot, GDPR Cookie Consent, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_consent_configure(
    plugin: str = "auto",
    analytics_category: str = None,
    marketing_category: str = None,
    functional_category: str = None,
    banner_position: str = None,
) -> dict:
    """Configure consent categories and cookie classification for the active consent plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_google_ads_conversion(
    conversion_id: str,
    conversion_label: str,
    method: str = "gtag",
    value: int = None,
    currency: str = "USD",
) -> dict:
    """Set up Google Ads conversion tracking via gtag.js or GTM"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_get_tracking_codes() -> dict:
    """List all tracking codes/pixels currently installed on the site (checks plugin settings, wp_head, wp_footer, options)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_remove_tracking_code(
    type: str,
    label: str = None,
) -> dict:
    """Remove a specific tracking code or pixel from the site. Requires wp-mcp companion plugin."""
    return _wp().post("/wp-mcp/v1/analytics/remove", json={"type": type, "label": label})

@mcp.tool()
def analytics_verify_tracking_chain() -> dict:
    """Verify the full tracking chain is set up correctly on this WordPress site. Checks: GTM installed, GA4 configured, Google Ads base tag present, conversion snippets active. Returns status for each layer and what's missing."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_install_gtag_base(
    conversion_id: str,
) -> dict:
    """Install the base gtag.js snippet for a Google Ads account (AW-XXXXXXXXX). Only the config snippet — no conversion event fired. Call this once per site before adding form or page conversions."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def analytics_detect_forms(
    page_id: int = None,
    page_slug: str = None,
) -> dict:
    """Scan a WordPress page's HTML content for all <form> elements and return their CSS selectors (id, class, action). Use this to find the right selector before setting up form conversion tracking."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_google_ads_form_conversion(
    conversion_id: str,
    send_to: str,
    form_selector: str,
    value: int = None,
    currency: str = "ILS",
    label: str = None,
) -> dict:
    """Inject JavaScript that fires a Google Ads conversion event ONLY when a specific form is submitted (by CSS selector). Use analytics_detect_forms first to find the correct selector."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_woo_google_ads_purchase(
    conversion_id: str,
    send_to: str,
    currency: str = "ILS",
) -> dict:
    """Inject Google Ads purchase conversion tracking for WooCommerce. Fires on the order-received (thank-you) page with the REAL order total read from the page DOM. Supports dynamic transaction_id from URL."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_woo_google_ads_add_to_cart(
    conversion_id: str,
    send_to: str,
    currency: str = "ILS",
    include_value: bool = True,
) -> dict:
    """Inject Google Ads add-to-cart conversion tracking for WooCommerce. Fires via the WooCommerce 'added_to_cart' jQuery event (works for both AJAX and standard add-to-cart)."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def analytics_woo_google_ads_checkout(
    conversion_id: str,
    send_to: str,
    currency: str = "ILS",
    include_value: bool = True,
) -> dict:
    """Inject Google Ads begin-checkout conversion tracking for WooCommerce. Fires when the visitor lands on the /checkout/ page (not the order-received page). Reads cart total from DOM."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_woo_google_ads_setup_full(
    conversion_id: str,
    purchase_send_to: str,
    add_to_cart_send_to: str,
    checkout_send_to: str,
    currency: str = "ILS",
) -> dict:
    """One-shot: Install ALL three WooCommerce Google Ads conversion snippets (purchase with dynamic value, add to cart, begin checkout) in a single call."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def analytics_google_ads_page_conversion(
    conversion_id: str,
    send_to: str,
    url_pattern: str,
    value: int = None,
    currency: str = "ILS",
    label: str = None,
) -> dict:
    """Inject JavaScript that fires a Google Ads conversion event when the visitor lands on a specific URL pattern (e.g. a thank-you page). Fires once per page load when URL matches."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)
