"""WordPress integrations tools -- generated by scripts/audit_wordpress_tools.py.

Do not edit by hand; re-run the script instead. Tools that failed the audit
are still emitted but listed in tool_registry._BROKEN_WORDPRESS_ACTIONS so
they are hidden from discovery.
"""
from __future__ import annotations

import base64 as base64_lib  # noqa: F401
import json  # noqa: F401
import mimetypes  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
from datetime import date, timedelta  # noqa: F401
from typing import Any, List, Optional  # noqa: F401
from urllib.parse import quote, urlparse  # noqa: F401

import requests  # noqa: F401

from mcp_instance import mcp
from permissions import require_editor  # noqa: F401

from .client import _trim, _unsupported_from_http, _wp  # noqa: F401
from ._helpers import *  # noqa: F401,F403 -- shared private helpers


@mcp.tool()
def amp_detect() -> dict:
    """Check if the AMP plugin is installed and active, and get its current configuration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def amp_configure(
    mode: str = None,
    all_templates_supported: bool = None,
    mobile_redirect: bool = None,
) -> dict:
    """Configure AMP plugin mode and settings"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def amp_validate_url(
    url: str = None,
    post_id: int = None,
) -> dict:
    """Validate an AMP page URL for AMP compliance errors"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def amp_supported_templates_set(
    posts: bool = None,
    pages: bool = None,
    archives: bool = None,
    categories: bool = None,
    tags: bool = None,
    search: bool = None,
    author: bool = None,
    homepage: bool = None,
) -> dict:
    """Configure which templates/content types use AMP (posts, pages, archives, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/amp", json=body)

@mcp.tool()
def pwa_detect() -> dict:
    """Check if a PWA plugin is installed (PWA for WP, Super Progressive Web Apps, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def pwa_manifest_get() -> dict:
    """Get the web app manifest (manifest.json) configuration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def pwa_manifest_set(
    name: str = None,
    short_name: str = None,
    description: str = None,
    start_url: str = "/",
    display: str = None,
    orientation: str = None,
    theme_color: str = None,
    background_color: str = None,
    icon_url: str = None,
    categories: list = None,
) -> dict:
    """Update the web app manifest settings (name, icons, colors, display mode)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "name")}
    return _wp().post(f"/wp-mcp/v1/amp/{name}", json=body)

@mcp.tool()
def pwa_service_worker_configure(
    caching_strategy: str = None,
    offline_page: str = None,
    precache_urls: list = None,
    cache_expiration_hours: int = 24,
    exclude_urls: list = None,
    push_notifications: bool = None,
) -> dict:
    """Configure service worker settings (caching strategy, offline page, push support)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/amp", params=params)

@mcp.tool()
def headless_get_rest_config() -> dict:
    """Get REST API configuration and available namespaces for headless WordPress use"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-json", params=params)

@mcp.tool()
def headless_cors_configure(
    allowed_origins: list,
    allowed_methods: list = None,
    allowed_headers: list = None,
    allow_credentials: bool = True,
    max_age: int = 86400,
) -> dict:
    """Configure CORS headers for headless WordPress frontend (allow cross-origin REST API access)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def booking_detect_plugin() -> dict:
    """Detect which booking/appointments plugin is installed (Amelia, BookingPress, Booked, Simply Schedule Appointments)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_slots_list(
    service_id: int,
    date: str,
    provider_id: int = None,
    date_end: str = None,
    location_id: int = None,
) -> dict:
    """List available booking time slots for a service/provider on a given date"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_create(
    service_id: int,
    date: str,
    time: str,
    provider_id: int = None,
    customer_id: int = None,
    customer_name: str = None,
    customer_email: str = None,
    customer_phone: str = None,
    duration: int = None,
    persons: int = 1,
    status: str = "approved",
    notes: str = None,
    location_id: int = None,
    custom_fields: dict = None,
) -> dict:
    """Create a new booking/appointment using whichever booking plugin is active"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/bookings", json=body)

@mcp.tool()
def booking_cancel(
    booking_id: int,
    reason: str = None,
    notify: bool = True,
) -> dict:
    """Cancel an existing booking/appointment"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_reschedule(
    booking_id: int,
    new_date: str,
    new_time: str,
    provider_id: int = None,
    notify: bool = True,
) -> dict:
    """Reschedule an existing booking to a new date/time"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_customers_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List customers/clients from the booking system"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_services_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    category_id: int = None,
    status: str = "active",
) -> dict:
    """List bookable services/appointment types"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_staff_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    service_id: int = None,
) -> dict:
    """List staff members/providers from the booking system"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_settings_get() -> dict:
    """Get booking plugin general settings (business hours, timezone, notification settings, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def booking_calendar_export(
    date_from: str,
    date_to: str,
    provider_id: int = None,
    service_id: int = None,
    status: str = "approved",
    per_page: int = 100,
    page: int = 1,
) -> dict:
    """Export bookings in a date range as a list (for calendar sync or reporting)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/bookings", params=params)

@mcp.tool()
def bp_members_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    type: str = "active",
    exclude: list = None,
) -> dict:
    """List BuddyPress community members"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/buddypress/v1/members", params=params)

@mcp.tool()
def bp_groups_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    type: str = "active",
    status: str = None,
    user_id: int = None,
) -> dict:
    """List BuddyPress groups"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/buddypress/v1/groups", params=params)

@mcp.tool()
def bp_groups_create(
    name: str,
    description: str = None,
    status: str = "public",
    creator_id: int = None,
    enable_forum: bool = False,
    parent_id: int = None,
) -> dict:
    """Create a new BuddyPress group"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/buddypress/v1/groups", json=body)

@mcp.tool()
def bp_groups_update(
    id: int,
    name: str = None,
    description: str = None,
    status: str = None,
    enable_forum: bool = None,
    parent_id: int = None,
) -> dict:
    """Update an existing BuddyPress group"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().put(f"/buddypress/v1/groups/{id}", json=body)

@mcp.tool()
def bp_groups_delete(
    id: int,
) -> dict:
    """Delete a BuddyPress group"""
    params = {}
    return _wp().delete(f"/buddypress/v1/groups/{id}", params=params)

@mcp.tool()
def bp_activity_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    type: str = None,
    component: str = None,
    user_id: int = None,
    group_id: int = None,
    display_comments: str = "threaded",
    after: str = None,
    before: str = None,
) -> dict:
    """List BuddyPress activity stream items"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/buddypress/v1/activity", params=params)

@mcp.tool()
def bp_activity_create(
    content: str,
    user_id: int = None,
    component: str = "activity",
    type: str = "activity_update",
    primary_item_id: int = None,
    secondary_item_id: int = None,
    hidden: bool = False,
) -> dict:
    """Create a new BuddyPress activity update"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/buddypress/v1/activity", json=body)

@mcp.tool()
def bp_messages_send(
    recipients: list,
    message: str,
    sender_id: int = None,
    subject: str = None,
    thread_id: int = None,
) -> dict:
    """Send a private message via BuddyPress"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/buddypress/v1/messages", json=body)

@mcp.tool()
def bp_friendship_create(
    initiator_id: int,
    friend_id: int,
    force: bool = False,
) -> dict:
    """Send a friendship request or create a friendship between two BuddyPress users"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/buddypress/v1/friends", json=body)

@mcp.tool()
def bp_xprofile_fields_list(
    per_page: int = 50,
    page: int = 1,
    profile_group_id: int = None,
    fetch_field_data: bool = False,
    member_type: str = None,
) -> dict:
    """List BuddyPress extended profile (xProfile) field groups and fields"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/buddypress/v1/xprofile/groups", params=params)

@mcp.tool()
def bp_xprofile_field_update(
    field_id: int,
    user_id: int,
    value: str,
) -> dict:
    """Update a BuddyPress xProfile field value for a user"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/buddypress/v1/xprofile/fields", json=body)

@mcp.tool()
def bbpress_forums_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
    parent: int = None,
    orderby: str = "menu_order",
    order: str = "asc",
) -> dict:
    """List bbPress forums"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def bbpress_forums_create(
    title: str,
    content: str = None,
    status: str = "publish",
    parent: int = None,
    type: str = "forum",
    menu_order: int = 0,
) -> dict:
    """Create a new bbPress forum"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def bbpress_topics_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    forum_id: int = None,
    author: int = None,
    status: str = "publish",
    orderby: str = "date",
    order: str = "desc",
    sticky: str = None,
) -> dict:
    """List bbPress topics (threads) in a forum"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def bbpress_topics_create(
    title: str,
    content: str,
    forum_id: int,
    author: int = None,
    status: str = "publish",
    sticky: bool = False,
    tags: list = None,
) -> dict:
    """Create a new bbPress topic (thread) in a forum"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def bbpress_replies_create(
    content: str,
    topic_id: int,
    forum_id: int = None,
    author: int = None,
    parent: int = None,
    status: str = "publish",
) -> dict:
    """Create a reply to a bbPress topic"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def acf_get_fields(
    id: int,
    type: str = "post",
    taxonomy: str = None,
) -> dict:
    """Get all ACF field values for a post, page, product, or user"""
    params = {}
    if type is not None: params["type"] = type
    if taxonomy is not None: params["taxonomy"] = taxonomy
    return _wp().get(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def acf_update_field(
    id: int,
    field_name: str,
    value: str,
    type: str = "post",
) -> dict:
    """Update a single ACF field value on a post/page/product"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def acf_bulk_update_fields(
    id: int,
    fields: dict,
    type: str = "post",
) -> dict:
    """Update multiple ACF fields on a post at once"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def acf_get_options_page(
    page_slug: str = "options",
) -> dict:
    """Get all ACF options page field values (global site options)"""
    params = {}
    if page_slug is not None: params["page_slug"] = page_slug
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def acf_update_options_field(
    field_name: str,
    value: str,
) -> dict:
    """Update an ACF options page field value"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def acf_get_field_groups(
    per_page: int = 50,
    search: str = None,
) -> dict:
    """List all ACF field groups"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if search is not None: params["search"] = search
    return _wp().get("/acf/v3/field-groups", params=params)

@mcp.tool()
def acf_get_field_group(
    id: int,
) -> dict:
    """Get a specific ACF field group with all its field definitions"""
    params = {}
    return _wp().get(f"/acf/v3/field-groups/{id}", params=params)

@mcp.tool()
def acf_get_post_meta(
    post_id: int,
    meta_key: str,
    post_type: str = "post",
) -> dict:
    """Get a specific meta value from any post/page/CPT (ACF-aware)"""
    params = {}
    if meta_key is not None: params["meta_key"] = meta_key
    return _wp().get(f"/wp/v2/posts/{post_id}", params=params)

@mcp.tool()
def crm_detect_plugin() -> dict:
    """Detect which CRM/email marketing plugin is active: FluentCRM, MailPoet, Groundhogg, MC4WP, or none"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def fluentcrm_contacts_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = None,
    tags: list = None,
    lists: list = None,
) -> dict:
    """List FluentCRM contacts/subscribers with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/fluent-crm/v2/subscribers", params=params)

@mcp.tool()
def fluentcrm_contact_create(
    email: str,
    first_name: str = None,
    last_name: str = None,
    status: str = "subscribed",
    lists: list = None,
    tags: list = None,
    custom_fields: dict = None,
    company: str = None,
    phone: str = None,
    address_line_1: str = None,
    city: str = None,
    state: str = None,
    country: str = None,
) -> dict:
    """Create a new contact in FluentCRM"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/fluent-crm/v2/subscribers", json=body)

@mcp.tool()
def fluentcrm_contact_update(
    id: int,
    email: str = None,
    first_name: str = None,
    last_name: str = None,
    status: str = None,
    custom_fields: dict = None,
    company: str = None,
    phone: str = None,
) -> dict:
    """Update an existing FluentCRM contact"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/fluent-crm/v2/subscribers/{id}", json=body)

@mcp.tool()
def fluentcrm_contact_delete(
    id: int,
) -> dict:
    """Delete a contact from FluentCRM"""
    params = {}
    return _wp().delete(f"/fluent-crm/v2/subscribers/{id}", params=params)

@mcp.tool()
def fluentcrm_contact_add_tag(
    id: int,
    tags: list,
) -> dict:
    """Add one or more tags to a FluentCRM contact"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/fluent-crm/v2/subscribers", json=body)

@mcp.tool()
def fluentcrm_contact_remove_tag(
    id: int,
    tags: list,
) -> dict:
    """Remove one or more tags from a FluentCRM contact"""
    params = {}
    return _wp().delete(f"/fluent-crm/v2/subscribers/{id}", params=params)

@mcp.tool()
def fluentcrm_lists_list(
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """List all FluentCRM contact lists"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/fluent-crm/v2/subscribers", params=params)

@mcp.tool()
def fluentcrm_lists_create(
    title: str,
    slug: str = None,
    description: str = None,
) -> dict:
    """Create a new contact list in FluentCRM"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/fluent-crm/v2/subscribers", json=body)

@mcp.tool()
def fluentcrm_campaigns_list(
    per_page: int = 20,
    page: int = 1,
    status: str = None,
) -> dict:
    """List all FluentCRM email campaigns"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/fluent-crm/v2/subscribers", params=params)

@mcp.tool()
def fluentcrm_campaigns_create(
    title: str,
    subject: str,
    body: str = None,
    from_name: str = None,
    from_email: str = None,
    lists: list = None,
    tags: list = None,
    template_id: int = None,
) -> dict:
    """Create a new email campaign in FluentCRM"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/fluent-crm/v2/subscribers", json=body)

@mcp.tool()
def fluentcrm_campaigns_send(
    campaign_id: int,
    scheduled_at: str = None,
) -> dict:
    """Send or schedule a FluentCRM campaign"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/fluent-crm/v2/subscribers", params=params)

@mcp.tool()
def mailpoet_subscribers_list(
    limit: int = 20,
    offset: int = 0,
    status: str = None,
    segment_id: int = None,
) -> dict:
    """List MailPoet subscribers with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def mailpoet_subscriber_add(
    email: str,
    first_name: str = None,
    last_name: str = None,
    status: str = "subscribed",
    segments: list = None,
) -> dict:
    """Add a new subscriber to MailPoet"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/email", json=body)

@mcp.tool()
def mailpoet_newsletters_list(
    limit: int = 20,
    offset: int = 0,
    type: str = None,
    status: str = None,
) -> dict:
    """List MailPoet newsletters/emails"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def mailpoet_newsletters_create(
    subject: str,
    type: str = "standard",
    body: str = None,
    preheader: str = None,
    segments: list = None,
    sender_name: str = None,
    sender_email: str = None,
    reply_to_name: str = None,
    reply_to_email: str = None,
) -> dict:
    """Create a new newsletter in MailPoet"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/email", json=body)

@mcp.tool()
def mailpoet_segments_list(
    limit: int = 50,
    offset: int = 0,
) -> dict:
    """List all MailPoet segments/lists"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def groundhogg_contacts_list(
    limit: int = 20,
    offset: int = 0,
    search: str = None,
    optin_status: int = None,
    tags_include: list = None,
) -> dict:
    """List Groundhogg contacts with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def groundhogg_contact_create(
    email: str,
    first_name: str = None,
    last_name: str = None,
    optin_status: int = 2,
    tags: list = None,
    meta: dict = None,
) -> dict:
    """Create a new contact in Groundhogg"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/email", json=body)

@mcp.tool()
def groundhogg_email_send(
    contact_id: int,
    email_id: int,
    subject: str = None,
    content: str = None,
) -> dict:
    """Send an email via Groundhogg to a contact or list of contacts"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def groundhogg_funnels_list(
    limit: int = 20,
    offset: int = 0,
    status: str = None,
) -> dict:
    """List all Groundhogg funnels (automation workflows)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/email", params=params)

@mcp.tool()
def crm_mailchimp_subscribe(
    email: str,
    first_name: str = None,
    last_name: str = None,
    list_id: str = None,
    tags: list = None,
    merge_fields: dict = None,
    status: str = "pending",
) -> dict:
    """Subscribe a contact to Mailchimp via MC4WP plugin or direct API integration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def crm_brevo_subscribe(
    email: str,
    first_name: str = None,
    last_name: str = None,
    list_ids: list = None,
    attributes: dict = None,
) -> dict:
    """Subscribe a contact to Brevo (formerly Sendinblue) via plugin integration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def crm_convertkit_subscribe(
    email: str,
    first_name: str = None,
    form_id: int = None,
    tag_ids: list = None,
    fields: dict = None,
) -> dict:
    """Subscribe a contact to ConvertKit via plugin or API integration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def tec_events_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
    start_date: str = None,
    end_date: str = None,
    categories: str = None,
    venue: int = None,
    organizer: int = None,
    featured: bool = None,
) -> dict:
    """List events from The Events Calendar plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def tec_events_create(
    title: str,
    start_date: str,
    end_date: str,
    description: str = None,
    excerpt: str = None,
    status: str = "draft",
    all_day: bool = False,
    timezone: str = None,
    venue: int = None,
    organizer: list = None,
    cost: str = None,
    currency_symbol: str = "$",
    website: str = None,
    featured: bool = False,
    image: int = None,
    categories: list = None,
    tags: list = None,
) -> dict:
    """Create a new event in The Events Calendar"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/tribe/events/v1/events", json=body)

@mcp.tool()
def tec_events_update(
    id: int,
    title: str = None,
    description: str = None,
    excerpt: str = None,
    status: str = None,
    start_date: str = None,
    end_date: str = None,
    all_day: bool = None,
    timezone: str = None,
    venue: int = None,
    organizer: list = None,
    cost: str = None,
    website: str = None,
    featured: bool = None,
    image: int = None,
    categories: list = None,
    tags: list = None,
) -> dict:
    """Update an existing event in The Events Calendar"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/tribe/events/v1/events/{id}", json=body)

@mcp.tool()
def tec_events_delete(
    id: int,
    force: bool = False,
) -> dict:
    """Delete an event from The Events Calendar"""
    params = {}
    if force is not None: params["force"] = force
    return _wp().delete(f"/tribe/events/v1/events/{id}", params=params)

@mcp.tool()
def tec_venues_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
) -> dict:
    """List venues from The Events Calendar"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def tec_venues_create(
    venue: str,
    description: str = None,
    address: str = None,
    city: str = None,
    state: str = None,
    province: str = None,
    zip: str = None,
    country: str = None,
    phone: str = None,
    website: str = None,
    show_map: bool = True,
    show_map_link: bool = True,
    status: str = "publish",
) -> dict:
    """Create a new venue for The Events Calendar"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/tribe/events/v1/events", json=body)

@mcp.tool()
def tec_organizers_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
) -> dict:
    """List organizers from The Events Calendar"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def tec_organizers_create(
    organizer: str,
    description: str = None,
    phone: str = None,
    email: str = None,
    website: str = None,
    status: str = "publish",
) -> dict:
    """Create a new organizer for The Events Calendar"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/tribe/events/v1/events", json=body)

@mcp.tool()
def tec_tickets_list(
    event_id: int,
    per_page: int = 20,
    page: int = 1,
    include_rsvp: bool = True,
) -> dict:
    """List tickets for an event (requires Event Tickets add-on)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def tec_tickets_create(
    event_id: int,
    title: str,
    description: str = None,
    price: str = None,
    type: str = "default",
    capacity: int = None,
    start_date: str = None,
    end_date: str = None,
    sku: str = None,
    min_per_order: int = 1,
    max_per_order: int = None,
) -> dict:
    """Create a ticket type for an event (requires Event Tickets add-on)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/tribe/events/v1/events", json=body)

@mcp.tool()
def tec_attendees_list(
    event_id: int,
    per_page: int = 50,
    page: int = 1,
    search: str = None,
) -> dict:
    """List attendees for an event (requires Event Tickets add-on)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def amelia_services_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    category_id: int = None,
    status: str = None,
) -> dict:
    """List Amelia booking services"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def amelia_services_create(
    name: str,
    category_id: int,
    duration: int,
    price: int,
    description: str = None,
    color: str = None,
    min_capacity: int = 1,
    max_capacity: int = 1,
    time_before: int = None,
    time_after: int = None,
    status: str = "visible",
    bring_anyone: bool = False,
    recurring: bool = False,
) -> dict:
    """Create a new Amelia booking service"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def amelia_employees_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    service_id: int = None,
    status: str = None,
) -> dict:
    """List Amelia employees (service providers)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def amelia_employees_create(
    first_name: str,
    last_name: str,
    email: str,
    phone: str = None,
    description: str = None,
    service_list: list = None,
    location_id: int = None,
    status: str = "visible",
    wp_user_id: int = None,
) -> dict:
    """Create a new Amelia employee (service provider)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def amelia_appointments_list(
    per_page: int = 20,
    page: int = 1,
    service_id: int = None,
    provider_id: int = None,
    customer_id: int = None,
    status: str = None,
    date_from: str = None,
    date_to: str = None,
) -> dict:
    """List Amelia appointments"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def amelia_appointments_create(
    service_id: int,
    provider_id: int,
    customer_id: int,
    booking_start: str,
    booking_end: str = None,
    status: str = "approved",
    notify_participants: bool = True,
    internal_notes: str = None,
    location_id: int = None,
    persons: int = 1,
) -> dict:
    """Create a new Amelia appointment"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def amelia_customers_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List Amelia customers"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def events_detect_plugin() -> dict:
    """Detect which events/booking plugin is installed (The Events Calendar, Amelia, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def events_list_universal(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    start_date: str = None,
    end_date: str = None,
) -> dict:
    """List events from whichever events plugin is active — auto-detects The Events Calendar or Amelia"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/tribe/events/v1/events", params=params)

@mcp.tool()
def cf7_list_forms(
    per_page: int = 20,
    search: str = None,
) -> dict:
    """List all Contact Form 7 forms"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if search is not None: params["search"] = search
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def cf7_get_form(
    id: int,
) -> dict:
    """Get a Contact Form 7 form by ID including its fields and configuration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def cf7_create_form(
    title: str,
    form_content: str = None,
    mail_subject: str = None,
    mail_to: str = None,
    mail_from: str = None,
    mail_body: str = None,
    mail_additional_headers: str = None,
    mail_2_active: bool = None,
    mail_2_to: str = None,
    mail_2_subject: str = None,
    mail_2_body: str = None,
) -> dict:
    """Create a new Contact Form 7 form"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/contact-form-7/v1/contact-forms", json=body)

@mcp.tool()
def cf7_update_form(
    id: int,
    title: str = None,
    form_content: str = None,
    mail_subject: str = None,
    mail_to: str = None,
    mail_body: str = None,
) -> dict:
    """Update a Contact Form 7 form"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/contact-form-7/v1/contact-forms/{id}", json=body)

@mcp.tool()
def cf7_delete_form(
    id: int,
) -> dict:
    """Delete a Contact Form 7 form"""
    params = {}
    return _wp().delete(f"/contact-form-7/v1/contact-forms/{id}", params=params)

@mcp.tool()
def cf7_get_shortcode(
    id: int,
) -> dict:
    """Get the shortcode to embed a CF7 form in a page"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def gf_list_forms(
    active: bool = None,
    per_page: int = 20,
) -> dict:
    """List all Gravity Forms"""
    params = {}
    if active is not None: params["active"] = active
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/gf/v2/forms", params=params)

@mcp.tool()
def gf_get_form(
    id: int,
) -> dict:
    """Get a Gravity Form by ID"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/gf/v2/forms", params=params)

@mcp.tool()
def gf_get_entries(
    form_id: int,
    per_page: int = 20,
    page: int = 1,
    status: str = "active",
    search: str = None,
    start_date: str = None,
    end_date: str = None,
) -> dict:
    """Get form entries/submissions from Gravity Forms"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/gf/v2/forms", params=params)

@mcp.tool()
def gf_get_entry(
    entry_id: int,
) -> dict:
    """Get a single Gravity Forms entry"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/gf/v2/forms", params=params)

@mcp.tool()
def gf_update_entry_status(
    entry_id: int,
    status: str,
) -> dict:
    """Update the status of a Gravity Forms entry"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "entry_id")}
    return _wp().post(f"/gf/v2/forms/{entry_id}", json=body)

@mcp.tool()
def gf_delete_entry(
    entry_id: int,
) -> dict:
    """Delete a Gravity Forms entry"""
    params = {}
    return _wp().delete(f"/gf/v2/forms/{entry_id}", params=params)

@mcp.tool()
def wpforms_list_forms(
    per_page: int = 20,
    search: str = None,
) -> dict:
    """List all WPForms"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if search is not None: params["search"] = search
    return _wp().get("/wpforms/v1/forms", params=params)

@mcp.tool()
def wpforms_get_entries(
    form_id: int,
    per_page: int = 20,
    page: int = 1,
    status: str = "read",
) -> dict:
    """Get WPForms entries"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpforms/v1/forms", params=params)

@mcp.tool()
def nf_list_forms(
    per_page: int = 20,
) -> dict:
    """List all Ninja Forms"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def nf_get_form(
    id: int,
) -> dict:
    """Get a Ninja Form by ID"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def nf_get_submissions(
    form_id: int,
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """Get Ninja Forms submissions"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def ld_courses_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
    orderby: str = "date",
    order: str = "desc",
) -> dict:
    """List LearnDash courses with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_courses_create(
    title: str,
    content: str = None,
    excerpt: str = None,
    status: str = "draft",
    featured_media: int = None,
    price_type: str = "open",
    price: str = None,
    materials: str = None,
    prerequisite_enabled: bool = False,
    prerequisite: list = None,
    points_enabled: bool = False,
    points_access: int = None,
) -> dict:
    """Create a new LearnDash course"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/ldlms/v2/sfwd-courses", json=body)

@mcp.tool()
def ld_courses_update(
    id: int,
    title: str = None,
    content: str = None,
    excerpt: str = None,
    status: str = None,
    featured_media: int = None,
    price_type: str = None,
    price: str = None,
    materials: str = None,
) -> dict:
    """Update an existing LearnDash course"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/ldlms/v2/sfwd-courses/{id}", json=body)

@mcp.tool()
def ld_courses_delete(
    id: int,
    force: bool = False,
) -> dict:
    """Delete a LearnDash course"""
    params = {}
    if force is not None: params["force"] = force
    return _wp().delete(f"/ldlms/v2/sfwd-courses/{id}", params=params)

@mcp.tool()
def ld_lessons_list(
    course: int = None,
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    orderby: str = "menu_order",
    order: str = "asc",
) -> dict:
    """List LearnDash lessons, optionally filtered by course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_lessons_create(
    title: str,
    course: int,
    content: str = None,
    status: str = "draft",
    featured_media: int = None,
    visible_after: int = None,
    visible_after_specific_date: str = None,
    forced_lesson_time: str = None,
    assignment_upload_enabled: bool = False,
    video_enabled: bool = False,
    video_url: str = None,
) -> dict:
    """Create a new LearnDash lesson"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/ldlms/v2/sfwd-courses", json=body)

@mcp.tool()
def ld_lessons_update(
    id: int,
    title: str = None,
    content: str = None,
    course: int = None,
    status: str = None,
    featured_media: int = None,
    visible_after: int = None,
    forced_lesson_time: str = None,
) -> dict:
    """Update an existing LearnDash lesson"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/ldlms/v2/sfwd-courses/{id}", json=body)

@mcp.tool()
def ld_topics_list(
    course: int = None,
    lesson: int = None,
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List LearnDash topics (sub-lessons), optionally filtered by course and lesson"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_topics_create(
    title: str,
    course: int,
    lesson: int,
    content: str = None,
    status: str = "draft",
    featured_media: int = None,
) -> dict:
    """Create a new LearnDash topic (sub-lesson)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/ldlms/v2/sfwd-courses", json=body)

@mcp.tool()
def ld_quizzes_list(
    course: int = None,
    lesson: int = None,
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List LearnDash quizzes, optionally filtered by course or lesson"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_quizzes_create(
    title: str,
    course: int,
    content: str = None,
    lesson: int = None,
    status: str = "draft",
    passing_percentage: int = 80,
    quiz_attempts: int = None,
    time_limit: int = None,
    certificate: int = None,
) -> dict:
    """Create a new LearnDash quiz"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/ldlms/v2/sfwd-courses", json=body)

@mcp.tool()
def ld_enroll_user(
    user_id: int,
    course_id: int,
) -> dict:
    """Enroll a user in a LearnDash course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_unenroll_user(
    user_id: int,
    course_id: int,
) -> dict:
    """Remove a user from a LearnDash course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_mark_complete(
    user_id: int,
    course_id: int,
    step_id: int,
) -> dict:
    """Mark a LearnDash course step (lesson/topic/quiz) as complete for a user"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def ld_user_progress(
    user_id: int,
    course_id: int,
) -> dict:
    """Get a user's progress in a LearnDash course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def lifter_courses_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
    orderby: str = "date",
    order: str = "desc",
) -> dict:
    """List LifterLMS courses"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def lifter_courses_create(
    title: str,
    content: str = None,
    excerpt: str = None,
    status: str = "draft",
    catalog_visibility: str = "catalog_search",
    access_opens_date: str = None,
    access_closes_date: str = None,
    enrollment_opens_date: str = None,
    enrollment_closes_date: str = None,
) -> dict:
    """Create a new LifterLMS course"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/courses", json=body)

@mcp.tool()
def lifter_lessons_list(
    parent: int = None,
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    orderby: str = "order",
    order: str = "asc",
) -> dict:
    """List LifterLMS lessons, optionally filtered by course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def lifter_enroll_user(
    student_id: int,
    post_id: int,
    trigger: str = "admin_enroll",
) -> dict:
    """Enroll a user in a LifterLMS course or membership"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def tutor_courses_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
    orderby: str = "date",
    order: str = "desc",
) -> dict:
    """List Tutor LMS courses"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def tutor_courses_create(
    title: str,
    content: str = None,
    excerpt: str = None,
    status: str = "draft",
    price: str = None,
    course_level: str = "all_levels",
    maximum_students: int = None,
    course_duration_hours: int = None,
    course_duration_minutes: int = None,
) -> dict:
    """Create a new Tutor LMS course"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/courses", json=body)

@mcp.tool()
def tutor_lessons_list(
    course_id: int = None,
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List Tutor LMS lessons, optionally filtered by course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def tutor_enroll_user(
    user_id: int,
    course_id: int,
) -> dict:
    """Enroll a user in a Tutor LMS course"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/courses", params=params)

@mcp.tool()
def mepr_memberships_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "publish",
) -> dict:
    """List all MemberPress memberships (plans)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_memberships_create(
    title: str,
    price: str,
    content: str = None,
    period: int = 1,
    period_type: str = "months",
    trial: bool = False,
    trial_days: int = None,
    trial_amount: str = None,
    limit_cycles: bool = False,
    limit_cycles_num: int = None,
    limit_cycles_action: str = "expire",
    group_id: int = None,
    status: str = "draft",
) -> dict:
    """Create a new MemberPress membership plan"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/mp/v1/memberships", json=body)

@mcp.tool()
def mepr_memberships_update(
    id: int,
    title: str = None,
    content: str = None,
    price: str = None,
    period: int = None,
    period_type: str = None,
    trial: bool = None,
    trial_days: int = None,
    trial_amount: str = None,
    status: str = None,
) -> dict:
    """Update an existing MemberPress membership plan"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/mp/v1/memberships/{id}", json=body)

@mcp.tool()
def mepr_members_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    membership: int = None,
    status: str = "all",
) -> dict:
    """List MemberPress members with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_grant_access(
    user_id: int,
    membership_id: int,
    trans_num: str = None,
) -> dict:
    """Grant a user access to a MemberPress membership"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_revoke_access(
    user_id: int,
    membership_id: int,
    transaction_id: int = None,
) -> dict:
    """Revoke a user's access to a MemberPress membership"""
    params = {}
    return _wp().delete("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_transactions_list(
    per_page: int = 20,
    page: int = 1,
    member: int = None,
    membership: int = None,
    status: str = None,
) -> dict:
    """List MemberPress transactions"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_coupons_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
) -> dict:
    """List MemberPress coupons"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_coupons_create(
    coupon_code: str,
    discount_amount: str,
    discount_type: str = "percent",
    valid_memberships: list = None,
    usage_count: int = None,
    starts_on: str = None,
    expires_on: str = None,
    first_payment_discount_type: str = None,
    first_payment_discount_amount: str = None,
    status: str = "publish",
) -> dict:
    """Create a new MemberPress coupon"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/mp/v1/memberships", json=body)

@mcp.tool()
def mepr_rules_list(
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """List MemberPress access rules"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/mp/v1/memberships", params=params)

@mcp.tool()
def mepr_rules_create(
    mepr_type: str,
    mepr_content: str,
    memberships: list,
    drip_enabled: bool = False,
    drip_amount: int = None,
    drip_type: str = None,
    drip_after: str = "registers",
    expires_enabled: bool = False,
    expires_amount: int = None,
    expires_type: str = None,
    unauth_excerpt_type: str = "default",
    unauth_message_type: str = "default",
    unauth_message: str = None,
) -> dict:
    """Create a MemberPress access rule to protect content"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/mp/v1/memberships", json=body)

@mcp.tool()
def pmp_levels_list(
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """List Paid Memberships Pro membership levels"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def pmp_levels_create(
    name: str,
    description: str = None,
    initial_payment: str = None,
    billing_amount: str = None,
    cycle_number: int = 1,
    cycle_period: str = "Month",
    billing_limit: int = None,
    trial_amount: str = None,
    trial_limit: int = None,
    expiration_number: int = None,
    expiration_period: str = None,
    confirmation: str = None,
    allow_signups: bool = True,
) -> dict:
    """Create a new Paid Memberships Pro membership level"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def pmp_members_list(
    per_page: int = 20,
    page: int = 1,
    level: int = None,
    status: str = "active",
    search: str = None,
) -> dict:
    """List Paid Memberships Pro members"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def pmp_orders_list(
    per_page: int = 20,
    page: int = 1,
    user_id: int = None,
    membership_id: int = None,
    status: str = None,
) -> dict:
    """List Paid Memberships Pro orders"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def pmp_discount_codes_create(
    code: str,
    starts: str = None,
    expires: str = None,
    uses: int = None,
    levels: list = None,
    initial_payment: str = None,
    billing_amount: str = None,
) -> dict:
    """Create a Paid Memberships Pro discount code"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def rcp_levels_list(
    per_page: int = 20,
    page: int = 1,
    status: str = "active",
) -> dict:
    """List Restrict Content Pro subscription levels"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def rcp_members_list(
    per_page: int = 20,
    page: int = 1,
    subscription: int = None,
    status: str = "active",
    search: str = None,
) -> dict:
    """List Restrict Content Pro members"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def um_forms_list(
    per_page: int = 20,
    page: int = 1,
    type: str = None,
) -> dict:
    """List Ultimate Member forms (registration, profile, login, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/contact-form-7/v1/contact-forms", params=params)

@mcp.tool()
def um_roles_list(
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """List Ultimate Member custom roles"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def wpml_languages_list() -> dict:
    """List all configured languages in WPML with status and default flag"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_language_add(
    code: str,
    default_locale: str = None,
    flag: str = None,
) -> dict:
    """Add a new language to WPML"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wpml/v1", json=body)

@mcp.tool()
def wpml_language_set_default(
    code: str,
) -> dict:
    """Set the default language in WPML"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wpml/v1", json=body)

@mcp.tool()
def wpml_post_get_translations(
    post_id: int,
    post_type: str = "post",
) -> dict:
    """Get all translations of a post in WPML (returns linked post IDs per language)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_post_create_translation(
    post_id: int,
    language: str,
    title: str = None,
    content: str = None,
    duplicate: bool = True,
) -> dict:
    """Create a translation of a post by duplicating it in WPML for a target language"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wpml/v1", json=body)

@mcp.tool()
def wpml_post_link_translation(
    source_post_id: int,
    target_post_id: int,
    language: str,
) -> dict:
    """Link two existing posts as translations of each other in WPML"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_strings_list(
    context: str = None,
    search: str = None,
    language: str = None,
    page: int = 1,
    per_page: int = 50,
) -> dict:
    """List translatable strings registered in WPML string translation"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_string_translate(
    string_id: int,
    language: str,
    value: str,
    status: int = 10,
) -> dict:
    """Translate a specific string in WPML string translation"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_auto_translate(
    post_id: int,
    target_languages: list,
    post_type: str = "post",
) -> dict:
    """Trigger WPML automatic translation (ATE) for a post"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_taxonomy_translate(
    term_id: int,
    taxonomy: str,
    language: str,
    name: str,
    slug: str = None,
    description: str = None,
) -> dict:
    """Translate a taxonomy term in WPML (categories, tags, custom taxonomies)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def wpml_media_translate(
    attachment_id: int,
    language: str,
    title: str = None,
    alt_text: str = None,
    caption: str = None,
    description: str = None,
) -> dict:
    """Translate media metadata (title, alt text, caption, description) for a specific language in WPML"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wpml/v1", params=params)

@mcp.tool()
def polylang_languages_list() -> dict:
    """List all languages configured in Polylang"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def polylang_post_translate(
    post_id: int,
    language: str,
    title: str = None,
    content: str = None,
    status: str = "draft",
) -> dict:
    """Create or link a translation for a post in Polylang"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def polylang_string_translate(
    group: str,
    name: str,
    language: str,
    value: str,
) -> dict:
    """Translate a registered string in Polylang's string translation module"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def polylang_sync_translation(
    post_id: int,
    sync_taxonomies: bool = True,
    sync_meta: bool = True,
    sync_featured_image: bool = True,
) -> dict:
    """Sync metadata (custom fields, taxonomies, featured image) between Polylang translations"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def translatepress_strings_list(
    language: str = None,
    search: str = None,
    status: str = "all",
    page: int = 1,
    per_page: int = 50,
) -> dict:
    """List translated strings from TranslatePress dictionary tables"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def translatepress_string_translate(
    original: str,
    translated: str,
    language: str,
) -> dict:
    """Add or update a string translation in TranslatePress"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def translatepress_auto_translate(
    enable: bool = None,
    engine: str = None,
    api_key: str = None,
) -> dict:
    """Configure or trigger TranslatePress automatic translation via Google Translate or DeepL"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def weglot_languages_list() -> dict:
    """List languages configured in Weglot"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def weglot_translate_url(
    url: str,
    language: str,
) -> dict:
    """Get the translated URL for a specific page in Weglot"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/i18n", params=params)

@mcp.tool()
def weglot_settings_update(
    api_key: str = None,
    original_language: str = None,
    destination_languages: list = None,
    auto_switch: bool = None,
    exclude_urls: list = None,
) -> dict:
    """Update Weglot plugin settings (original language, destination languages, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/i18n", json=body)

@mcp.tool()
def affiliates_detect_plugin() -> dict:
    """Detect which affiliate/referral plugin is installed (AffiliateWP, YITH Affiliates, SliceWP)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/affiliates", params=params)

@mcp.tool()
def affiliates_list(
    per_page: int = 20,
    page: int = 1,
    status: str = "active",
    search: str = None,
    orderby: str = "date",
    order: str = "desc",
) -> dict:
    """List affiliates with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/affiliates", params=params)

@mcp.tool()
def affiliates_create(
    user_id: int,
    payment_email: str = None,
    rate: int = None,
    rate_type: str = "percentage",
    status: str = "active",
    notes: str = None,
) -> dict:
    """Create a new affiliate account"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/affiliates", json=body)

@mcp.tool()
def affiliates_update(
    affiliate_id: int,
    status: str = None,
    rate: int = None,
    rate_type: str = None,
    payment_email: str = None,
    notes: str = None,
) -> dict:
    """Update an existing affiliate's settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/affiliates", json=body)

@mcp.tool()
def affiliates_referrals_list(
    per_page: int = 20,
    page: int = 1,
    affiliate_id: int = None,
    status: str = "unpaid",
    date_min: str = None,
    date_max: str = None,
    orderby: str = "date",
    order: str = "desc",
) -> dict:
    """List referral history with optional filters"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/affiliates", params=params)

@mcp.tool()
def affiliates_payouts_list(
    per_page: int = 20,
    page: int = 1,
    affiliate_id: int = None,
    status: str = None,
    date_min: str = None,
    date_max: str = None,
) -> dict:
    """List affiliate payouts"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/affiliates", params=params)

@mcp.tool()
def affiliates_payout_create(
    affiliate_id: int,
    amount: int,
    referral_ids: list = None,
    payout_method: str = "manual",
    notes: str = None,
) -> dict:
    """Create a payout for an affiliate (mark referrals as paid)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/affiliates", json=body)

@mcp.tool()
def affiliates_links_generate(
    affiliate_id: int,
    url: str,
    campaign: str = None,
) -> dict:
    """Generate an affiliate referral link for a given URL"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/affiliates", params=params)

@mcp.tool()
def affiliates_commission_set(
    rate: int,
    affiliate_id: int = None,
    rate_type: str = "percentage",
    cookie_duration: int = None,
    per_product_rates: list = None,
) -> dict:
    """Set global or per-affiliate commission rate and type"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/affiliates", json=body)

@mcp.tool()
def rest_discover_routes(
    namespace: str = None,
) -> dict:
    """Discover all available REST API routes by fetching the root /wp-json/ index"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-json", params=params)

@mcp.tool()
def rest_get_route_info(
    route: str,
) -> dict:
    """Get detailed information about a specific REST API route (methods, arguments, schema)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-json", params=params)

@mcp.tool()
def rest_custom_call(
    method: str,
    endpoint: str,
    body: dict = None,
    params: dict = None,
) -> dict:
    """Make an arbitrary REST API call to any endpoint with any HTTP method (GET, POST, PUT, PATCH, DELETE)"""
    m = (method or "GET").upper()
    wp = _wp()
    if m == "GET":
        return wp.get(endpoint, params=params)
    elif m == "POST":
        return wp.post(endpoint, json=body)
    elif m == "PUT":
        return wp.put(endpoint, json=body)
    elif m == "PATCH":
        return wp.patch(endpoint, json=body)
    elif m == "DELETE":
        return wp.delete(endpoint, params=params)
    return {"error": f"Unsupported method: {method}"}

@mcp.tool()
def rest_namespace_list() -> dict:
    """List all registered REST API namespaces"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-json", params=params)

@mcp.tool()
def rest_test_endpoint(
    endpoint: str,
    method: str = "GET",
) -> dict:
    """Test if a specific REST API endpoint is responding and accessible"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-json", params=params)

@mcp.tool()
def graphql_detect() -> dict:
    """Check if WPGraphQL plugin is installed and the /graphql endpoint is available"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/graphql", params=params)

@mcp.tool()
def graphql_query(
    query: str,
    variables: dict = None,
    operation_name: str = None,
) -> dict:
    """Execute a GraphQL query against the WPGraphQL endpoint"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/graphql", params=params)

@mcp.tool()
def graphql_introspect(
    type_name: str = None,
) -> dict:
    """Run a GraphQL introspection query to discover the schema (types, queries, mutations)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/graphql", params=params)

@mcp.tool()
def graphql_mutation(
    mutation: str,
    variables: dict = None,
) -> dict:
    """Execute a GraphQL mutation against the WPGraphQL endpoint"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/graphql", params=params)

@mcp.tool()
def rest_batch_request(
    requests: list = None,
    validation: str = "normal",
) -> dict:
    """Execute multiple REST API requests in a single batch call using the WP REST batch endpoint (/wp/v2/batch)"""
    body = {k: v for k, v in {"requests": requests, "validation": validation}.items() if v is not None}
    return _wp().post("/wp/v2/batch", json=body)
