"""WordPress ops tools -- generated by scripts/audit_wordpress_tools.py.

Do not edit by hand; re-run the script instead. Tools that failed the audit
are still emitted but listed in tool_registry._BROKEN_WORDPRESS_ACTIONS so
they are hidden from discovery.
"""
from __future__ import annotations

import base64 as base64_lib  # noqa: F401
import json  # noqa: F401
import mimetypes  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
from datetime import date, timedelta  # noqa: F401
from typing import Any, List, Optional  # noqa: F401
from urllib.parse import quote, urlparse  # noqa: F401

import requests  # noqa: F401

from mcp_instance import mcp
from permissions import require_editor  # noqa: F401

from .client import _trim, _unsupported_from_http, _wp  # noqa: F401
from ._helpers import *  # noqa: F401,F403 -- shared private helpers


@mcp.tool()
def a11y_audit_page(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Audit a WordPress page for WCAG 2.2 AA accessibility issues (alt text, headings, contrast, form labels, ARIA landmarks, skip link)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_alt_texts(
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Find images without alt text across the site (checks media library and page content)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_heading_hierarchy(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Verify H1-H6 heading structure on a specific page for proper document outline"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_form_labels(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Verify all form inputs have associated labels on a specific page"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_link_text(
    page_id: int = None,
    post_type: str = "page",
    per_page: int = 10,
) -> dict:
    """Find generic link text like 'click here', 'read more', 'here' across pages (WCAG 2.4.4)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_color_contrast(
    foreground: str,
    background: str,
    font_size: int = 16,
    is_bold: bool = False,
) -> dict:
    """Check color contrast ratio between text and background colors (WCAG 2.2 AA requires 4.5:1 for normal text, 3:1 for large text)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_check_aria_landmarks(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Verify ARIA landmark roles (main, nav, header/banner, footer/contentinfo, search) on a page"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_fix_missing_alt(
    per_page: int = 50,
    alt_template: str = "{title}",
    dry_run: bool = True,
) -> dict:
    """Bulk add placeholder alt text to images missing alt attributes in the media library"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_generate_alt_text(
    image_ids: list = None,
    per_page: int = 10,
) -> dict:
    """Generate descriptive alt text suggestions for images (returns image URLs and titles for an AI agent to write alt text)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_skip_link_check(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Verify that a skip navigation link exists at the top of the page (WCAG 2.4.1)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_detect_plugin() -> dict:
    """Detect installed accessibility plugins (WP Accessibility, One Click Accessibility, UserWay, AccessiBe, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def a11y_widget_configure(
    plugin: str,
    enabled: bool = None,
    position: str = None,
    icon_size: str = None,
    features: dict = None,
) -> dict:
    """Configure accessibility widget/overlay settings for detected accessibility plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def backup_detect_plugin() -> dict:
    """Detect which backup plugin is installed (UpdraftPlus, All-in-One WP Migration, Duplicator, BackupBuddy, BlogVault, WPvivid, or none)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_updraft_run(
    type: str = "full",
    label: str = None,
) -> dict:
    """Trigger an UpdraftPlus backup (full or incremental)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_updraft_list() -> dict:
    """List existing UpdraftPlus backups with dates and sizes"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_updraft_restore(
    backup_id: str,
    components: list = None,
) -> dict:
    """Trigger an UpdraftPlus restore from a specific backup"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_updraft_schedule_get() -> dict:
    """Get current UpdraftPlus backup schedule settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/updraftplus/v1/backup", json=body)

@mcp.tool()
def backup_updraft_schedule_set(
    files_schedule: str = None,
    db_schedule: str = None,
    retain_files: int = None,
    retain_db: int = None,
) -> dict:
    """Set UpdraftPlus backup schedule"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/updraftplus/v1/backup", json=body)

@mcp.tool()
def backup_updraft_settings_get() -> dict:
    """Get UpdraftPlus plugin settings (remote storage, email notifications, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_aio_export(
    format: str = "file",
    exclude_spam_comments: bool = True,
    exclude_post_revisions: bool = False,
    exclude_media: bool = False,
) -> dict:
    """Trigger an All-in-One WP Migration export"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_aio_import(
    file_path: str,
) -> dict:
    """Trigger an All-in-One WP Migration import from uploaded file"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_duplicator_list() -> dict:
    """List Duplicator packages (backup archives)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_duplicator_create(
    name: str = None,
    notes: str = None,
    archive_filter_dirs: str = None,
    archive_filter_exts: str = None,
) -> dict:
    """Create a new Duplicator backup package"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/updraftplus/v1/backup", json=body)

@mcp.tool()
def backup_wpvivid_run(
    type: str = "full",
) -> dict:
    """Trigger a WPvivid backup"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_wpvivid_list() -> dict:
    """List existing WPvivid backups"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_get_status() -> dict:
    """Get universal backup status — checks all supported backup plugins for last backup info"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/updraftplus/v1/backup", params=params)

@mcp.tool()
def backup_export_db_tables(
    tables: list = None,
    format: str = "sql",
) -> dict:
    """Export specific database tables via companion plugin or provide WP-CLI/mysqldump commands"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def cdn_detect_service() -> dict:
    """Detect which CDN service is active on the site (Cloudflare, Bunny, StackPath, KeyCDN, CloudFront, or none) by inspecting response headers"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_cloudflare_purge(
    urls: list = None,
    purge_everything: bool = False,
) -> dict:
    """Purge Cloudflare cache via companion plugin endpoint or Cloudflare plugin REST API"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_cloudflare_dev_mode_toggle(
    enabled: bool,
) -> dict:
    """Toggle Cloudflare Development Mode on/off (bypasses cache for 3 hours)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def cdn_cloudflare_security_level(
    level: str,
) -> dict:
    """Set Cloudflare security level (essentially_off, low, medium, high, under_attack)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me/application-passwords", params=params)

@mcp.tool()
def cdn_bunny_purge(
    url: str = None,
) -> dict:
    """Purge Bunny CDN cache via companion plugin endpoint"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_configure_wp_rocket_cdn(
    cdn_url: str,
    enabled: bool = True,
) -> dict:
    """Configure CDN CNAME/URL in WP Rocket settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/cdn", json=body)

@mcp.tool()
def cdn_configure_w3tc_cdn(
    cdn_url: str,
    cdn_type: str = "pull",
    enabled: bool = True,
) -> dict:
    """Configure CDN settings in W3 Total Cache"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/cdn", json=body)

@mcp.tool()
def cdn_offload_media_s3(
    provider: str = None,
    bucket: str = None,
    region: str = None,
    copy_to_s3: bool = True,
    serve_from_s3: bool = True,
    remove_local_file: bool = False,
) -> dict:
    """Configure WP Offload Media (WP Offload S3) settings for offloading media to Amazon S3 or compatible storage"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_offload_media_cloudinary(
    cloud_name: str = None,
    auto_sync: bool = True,
    image_optimization: bool = True,
    lazy_loading: bool = False,
) -> dict:
    """Configure Cloudinary plugin settings for media offloading and transformation"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_get_status() -> dict:
    """Check if CDN is currently working by inspecting headers and response patterns"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cdn_configure_url_rewriting(
    cdn_url: str,
    include_dirs: str = "wp-content,wp-includes",
    exclude_extensions: str = "php",
) -> dict:
    """Configure media URL rewriting to use CDN domain via functions.php or plugin settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/cdn", json=body)

@mcp.tool()
def cdn_test_response_headers(
    url: str = None,
) -> dict:
    """Test CDN response headers for a given URL to verify caching, cache-hit status, and CDN identification"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cdn", params=params)

@mcp.tool()
def cron_list_events(
    search: str = None,
) -> dict:
    """List all scheduled WordPress cron events with hook names, schedules, and next run times"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_list_schedules() -> dict:
    """List all registered cron schedule intervals (hourly, daily, custom, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_create_event(
    hook: str,
    recurrence: str = None,
    timestamp: int = None,
    args: list = None,
) -> dict:
    """Schedule a new WordPress cron event"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/cron", json=body)

@mcp.tool()
def cron_delete_event(
    hook: str,
    timestamp: int = None,
) -> dict:
    """Unschedule/delete a WordPress cron event by hook name"""
    params = {}
    return _wp().delete("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_run_now(
    hook: str,
) -> dict:
    """Execute a cron event immediately (trigger the hook now)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_next_run(
    hook: str,
) -> dict:
    """Get the next scheduled run time for a specific cron event"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_register_schedule(
    name: str,
    interval: int,
    display: str,
) -> dict:
    """Register a custom cron schedule interval"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/cron", json=body)

@mcp.tool()
def cron_wp_cron_status() -> dict:
    """Check if WP-Cron is working correctly (DISABLE_WP_CRON status, missed events, spawn test)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_disable_wp_cron(
    interval_minutes: int = 5,
) -> dict:
    """Get instructions to disable WP-Cron and use a real server cron job instead"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_detect_plugin() -> dict:
    """Detect if WP-Crontrol or Advanced Cron Manager is installed"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_crontrol_list() -> dict:
    """List cron events via WP-Crontrol plugin (if installed)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/cron", params=params)

@mcp.tool()
def cron_crontrol_add(
    hook: str,
    recurrence: str = None,
    next_run: str = "now",
    php_code: str = None,
) -> dict:
    """Add a new cron event via WP-Crontrol plugin (if installed)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/cron", json=body)

@mcp.tool()
def db_tables_list() -> dict:
    """List all database tables with their row counts and sizes via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_table_size(
    table: str,
) -> dict:
    """Get size and row count for a specific database table"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_query_select(
    query: str,
    limit: int = 100,
) -> dict:
    """Execute a safe SELECT query via companion plugin (only SELECT statements allowed)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_query_count(
    table: str,
    where: str = None,
) -> dict:
    """Execute a COUNT query via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_optimize_tables(
    tables: list = None,
) -> dict:
    """Run OPTIMIZE TABLE on specified tables or all tables via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_repair_tables(
    tables: list = None,
) -> dict:
    """Run REPAIR TABLE on specified tables or all tables via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_get_options(
    option_names: list,
) -> dict:
    """Read one or more values from the wp_options table"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_set_option(
    option_name: str,
    option_value: str,
    autoload: str = "yes",
) -> dict:
    """Set a value in the wp_options table"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/db", json=body)

@mcp.tool()
def db_delete_option(
    option_name: str,
) -> dict:
    """Delete an option from the wp_options table"""
    params = {}
    return _wp().delete("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_search_options(
    pattern: str,
    limit: int = 50,
) -> dict:
    """Search wp_options by key pattern (SQL LIKE pattern)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_get_autoloaded_size() -> dict:
    """Get total size of autoloaded options in wp_options (large autoload can slow sites)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_cleanup_orphaned_postmeta(
    dry_run: bool = True,
) -> dict:
    """Find and delete postmeta entries whose parent post no longer exists"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_cleanup_orphaned_commentmeta(
    dry_run: bool = True,
) -> dict:
    """Find and delete commentmeta entries whose parent comment no longer exists"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_cleanup_orphaned_termmeta(
    dry_run: bool = True,
) -> dict:
    """Find and delete termmeta entries whose parent term no longer exists"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def db_get_table_prefix() -> dict:
    """Get the current WordPress database table prefix"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/db", params=params)

@mcp.tool()
def dev_wp_cli_run(
    command: str,
    args: list = None,
) -> dict:
    """Execute a WP-CLI command via companion plugin endpoint (requires companion plugin on the server)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_debug_mode_get() -> dict:
    """Read current WP_DEBUG and related debug constant status"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_debug_mode_set(
    wp_debug: bool = None,
    wp_debug_log: bool = None,
    wp_debug_display: bool = None,
    script_debug: bool = None,
    savequeries: bool = None,
) -> dict:
    """Enable or disable WP_DEBUG and related constants via companion plugin (modifies wp-config.php)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/dev", json=body)

@mcp.tool()
def dev_debug_log_read(
    lines: int = 100,
    search: str = None,
) -> dict:
    """Read the WordPress debug.log file contents via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_debug_log_clear() -> dict:
    """Clear/truncate the WordPress debug.log file via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_error_log_read(
    lines: int = 100,
    search: str = None,
) -> dict:
    """Read the PHP error log file via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_query_monitor_data(
    panel: str = "all",
) -> dict:
    """Retrieve Query Monitor plugin data (queries, hooks, HTTP requests, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_code_snippets_list(
    status: str = "all",
    per_page: int = 50,
) -> dict:
    """List all code snippets from the Code Snippets plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_code_snippets_create(
    name: str,
    code: str,
    description: str = None,
    scope: str = "global",
    priority: int = 10,
    active: bool = False,
) -> dict:
    """Create a new code snippet via the Code Snippets plugin"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/dev", json=body)

@mcp.tool()
def dev_code_snippets_update(
    id: int,
    name: str = None,
    code: str = None,
    description: str = None,
    scope: str = None,
    priority: int = None,
) -> dict:
    """Update an existing code snippet"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp-mcp/v1/dev/{id}", json=body)

@mcp.tool()
def dev_code_snippets_toggle(
    id: int,
    active: bool,
) -> dict:
    """Activate or deactivate a code snippet"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_code_snippets_delete(
    id: int,
) -> dict:
    """Delete a code snippet"""
    params = {}
    return _wp().delete(f"/wp-mcp/v1/dev/{id}", params=params)

@mcp.tool()
def dev_hooks_list(
    type: str = "all",
    search: str = None,
) -> dict:
    """List registered WordPress hooks/filters via companion plugin (actions and filters currently registered)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_constants_get(
    constants: list = None,
) -> dict:
    """Read WordPress constants (WP_DEBUG, ABSPATH, etc.) via companion plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_constants_set(
    name: str,
    value: str,
) -> dict:
    """Set/update WordPress constants in wp-config.php via companion plugin"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "name")}
    return _wp().post(f"/wp-mcp/v1/dev/{name}", json=body)

@mcp.tool()
def dev_wp_config_read() -> dict:
    """Read wp-config.php contents via companion plugin (sensitive data may be redacted)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_file_read(
    path: str,
) -> dict:
    """Read a theme or plugin file via companion plugin (restricted to wp-content directory)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_file_write(
    path: str,
    content: str,
    backup: bool = True,
) -> dict:
    """Write/update a theme or plugin file via companion plugin (restricted to wp-content directory)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_theme_file_list(
    subdirectory: str = None,
) -> dict:
    """List files in the active theme directory via companion plugin or theme file editor REST API"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def dev_eval_php(
    code: str,
) -> dict:
    """Execute arbitrary PHP code via companion plugin. Use with extreme caution! Code runs with full WordPress context."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/dev", params=params)

@mcp.tool()
def multisite_detect() -> dict:
    """Check if the WordPress installation is a multisite network"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_sites_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    status: str = "all",
) -> dict:
    """List all sites in the multisite network (requires network admin privileges)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_site_create(
    title: str,
    domain: str = None,
    path: str = None,
    admin_user_id: int = None,
    options: dict = None,
) -> dict:
    """Create a new site in the multisite network"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/sites", json=body)

@mcp.tool()
def multisite_site_update(
    site_id: int,
    title: str = None,
    description: str = None,
    domain: str = None,
    path: str = None,
    public: int = None,
    language: str = None,
) -> dict:
    """Update settings for a specific site in the network"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "site_id")}
    return _wp().post(f"/wp/v2/sites/{site_id}", json=body)

@mcp.tool()
def multisite_site_delete(
    site_id: int,
    drop_tables: bool = False,
) -> dict:
    """Delete a site from the multisite network (irreversible)"""
    params = {}
    return _wp().delete(f"/wp/v2/sites/{site_id}", params=params)

@mcp.tool()
def multisite_site_activate(
    site_id: int,
) -> dict:
    """Activate a deactivated site in the network"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_site_deactivate(
    site_id: int,
) -> dict:
    """Deactivate (suspend) a site in the network without deleting it"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_site_archive(
    site_id: int,
    archive: bool = True,
) -> dict:
    """Archive a site in the network (makes it inaccessible but preserved)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_users_list(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    role: str = None,
) -> dict:
    """List users across the multisite network (network-wide)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_user_add_to_site(
    user_id: int,
    site_id: int,
    role: str,
) -> dict:
    """Add an existing network user to a specific site with a given role"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/sites", json=body)

@mcp.tool()
def multisite_user_remove_from_site(
    user_id: int,
    site_id: int,
) -> dict:
    """Remove a user from a specific site in the network (does not delete the user)"""
    params = {}
    return _wp().delete(f"/wp/v2/sites/{site_id}", params=params)

@mcp.tool()
def multisite_themes_network_enable(
    theme: str,
    enabled: bool,
) -> dict:
    """Enable or disable a theme network-wide so subsites can use it"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_plugins_network_activate(
    plugin: str,
    activate: bool,
) -> dict:
    """Network-activate or deactivate a plugin across all sites"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_network_settings_get() -> dict:
    """Get network-wide settings (registration, upload limits, allowed themes, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/sites", params=params)

@mcp.tool()
def multisite_network_settings_update(
    registration: str = None,
    upload_max_filesize: int = None,
    blog_upload_space: int = None,
    upload_filetypes: str = None,
    site_name: str = None,
    admin_email: str = None,
    first_post: str = None,
    add_new_users: bool = None,
    menu_items: dict = None,
) -> dict:
    """Update network-wide settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/sites", json=body)

@mcp.tool()
def privacy_policy_page_get() -> dict:
    """Get the designated privacy policy page (ID, title, URL, content)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_policy_page_set(
    page_id: int,
) -> dict:
    """Set the privacy policy page by page ID"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "page_id")}
    return _wp().post(f"/wp/v2/users/me/{page_id}", json=body)

@mcp.tool()
def privacy_export_request_create(
    email: str,
) -> dict:
    """Create a personal data export request for a user (GDPR Article 15 — Right of Access)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/users/me", json=body)

@mcp.tool()
def privacy_erasure_request_create(
    email: str,
) -> dict:
    """Create a personal data erasure request for a user (GDPR Article 17 — Right to Erasure)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/users/me", json=body)

@mcp.tool()
def privacy_requests_list(
    type: str = "all",
    status: str = "all",
    per_page: int = 20,
) -> dict:
    """List pending privacy data requests (exports and erasures)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_cookie_banner_detect() -> dict:
    """Detect installed cookie consent/banner plugins (CookieYes, Complianz, Cookie Notice, GDPR Cookie Consent, CookieBot, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_cookie_banner_configure(
    plugin: str,
    banner_text: str = None,
    accept_text: str = None,
    reject_text: str = None,
    policy_url: str = None,
    position: str = None,
    style: str = None,
    auto_block_scripts: bool = None,
) -> dict:
    """Configure cookie consent banner settings for the detected plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_cookie_categories_set(
    plugin: str,
    categories: list,
) -> dict:
    """Configure cookie categories (necessary, analytics, marketing, preferences/functional)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/users/me", json=body)

@mcp.tool()
def privacy_data_retention_configure(
    comments_retention_days: int = None,
    wc_orders_retention_days: int = None,
    form_entries_retention_days: int = None,
    analytics_retention_days: int = None,
    inactive_user_notification_days: int = None,
) -> dict:
    """Configure data retention rules (comment data, WooCommerce orders, form entries, analytics)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_consent_log_list(
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """List cookie consent log entries (requires a consent logging plugin)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_dpa_info() -> dict:
    """Get data processing agreement (DPA) information and checklist for GDPR compliance"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def privacy_ccpa_configure(
    plugin: str,
    enable_do_not_sell: bool = None,
    do_not_sell_text: str = "Do Not Sell My Personal Information",
    do_not_sell_url: str = None,
    gpc_support: bool = None,
) -> dict:
    """Configure California Consumer Privacy Act (CCPA) / CPRA settings — 'Do Not Sell' link, opt-out mechanism"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/users/me", params=params)

@mcp.tool()
def clone_analyze_url(
    url: str,
) -> dict:
    """Fetch any website URL and extract its full structure: colors, fonts, layout sections, images, and text content. Returns a structured JSON analysis for cloning into WordPress/Elementor."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_analyze_full_site(
    url: str,
    max_pages: int = None,
) -> dict:
    """Crawl multiple pages of a website to extract global structure: all page URLs, menu, footer, global colors, and fonts."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_download_images(
    image_urls: list,
    post_id: int = None,
) -> dict:
    """Download images from analyzed URLs and upload them to the WordPress Media Library. Returns a mapping of original URL to new WP media ID and URL."""
    import requests as _req
    wp = _wp()
    results = {}
    for img_url in (image_urls or []):
        try:
            r = _req.get(img_url, timeout=30)
            r.raise_for_status()
            ct = r.headers.get("Content-Type", "image/jpeg").split(";")[0].strip()
            fname = img_url.rstrip("/").split("/")[-1].split("?")[0] or "image.jpg"
            media = wp.upload_media(fname, r.content, ct)
            results[img_url] = {"id": media.get("id"), "url": media.get("source_url")}
        except Exception as exc:
            results[img_url] = {"error": str(exc)}
    return {"results": results, "count": len(results)}

@mcp.tool()
def clone_extract_colors(
    url: str,
) -> dict:
    """Extract the color palette from a website URL. Returns primary, secondary, accent, background, and text colors with usage counts."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_extract_fonts(
    url: str,
) -> dict:
    """Extract font families used on a website URL. Returns heading font, body font, and full list with weights."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_extract_menu(
    url: str,
) -> dict:
    """Extract the navigation menu structure from a website URL, including nested sub-menu items."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_extract_footer(
    url: str,
) -> dict:
    """Extract footer content (text, links, HTML) from a website URL."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_build_page_plan(
    analysis: dict,
) -> dict:
    """From a clone analysis result, create an ordered Elementor page-building plan: which sections to create, which widgets to use, and in what order."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/ldlms/v2/sfwd-courses", params=params)

@mcp.tool()
def clone_create_page_from_url(
    source_url: str,
    page_title: str = None,
    page_status: str = None,
) -> dict:
    """Full automated cloning: analyze a URL, download its images, create a WordPress page, and build Elementor sections/widgets to replicate the original layout."""
    body = {"title": page_title or source_url, "status": page_status or "draft", "template": "elementor_canvas"}
    return _wp().post("/wp/v2/pages", json=body)

@mcp.tool()
def clone_replicate_section(
    section_data: dict,
    page_id: int,
    position: int = None,
) -> dict:
    """Replicate a specific section type (hero, features, pricing, etc.) from analysis data into an existing Elementor page."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_map_colors_to_kit(
    primary: str,
    secondary: str = None,
    accent: str = None,
    text: str = None,
    background: str = None,
) -> dict:
    """Apply extracted colors to the Elementor global kit (site-wide color settings)."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_map_fonts_to_kit(
    heading_font: str,
    body_font: str,
) -> dict:
    """Apply extracted fonts to the Elementor global kit (heading and body typography)."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_full_site(
    source_url: str,
    max_pages: int = None,
) -> dict:
    """Master tool: clone an entire website. Crawls pages, downloads images, creates all WordPress pages, sets up menus, applies colors/fonts, and sets the homepage."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_get_page_html(
    url: str,
) -> dict:
    """Fetch the raw HTML of any URL via the companion plugin or direct request."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_parse_html_sections(
    html: str,
    base_url: str = None,
) -> dict:
    """Parse raw HTML into semantic sections (header, hero, features, testimonials, pricing, footer, etc.)."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_detect_layout_type(
    url: str,
) -> dict:
    """Detect the type of a page: landing, blog, ecommerce, portfolio, corporate, or directory."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_suggest_elementor_widgets(
    sections: list,
) -> dict:
    """For each detected section type, suggest which Elementor widgets should be used to replicate it."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/elementor_library", params=params)

@mcp.tool()
def clone_create_style_guide(
    url: str,
) -> dict:
    """Generate a complete style guide from an analyzed site: colors, fonts, spacing patterns, button styles."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def clone_compare_original_vs_clone(
    original_url: str,
    clone_page_id: int,
) -> dict:
    """Compare the original URL's text content against a cloned WordPress page to find differences."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def clone_status() -> dict:
    """Get the status of the most recent or ongoing clone operation stored in WP options."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def smtp_detect_plugin() -> dict:
    """Detect which SMTP plugin is active: WP Mail SMTP, FluentSMTP, Post SMTP, or none"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_configure(
    host: str,
    port: int,
    plugin: str = "auto",
    username: str = None,
    password: str = None,
    encryption: str = "tls",
    from_email: str = None,
    from_name: str = None,
    auth: bool = True,
) -> dict:
    """Set SMTP provider settings (host, port, user, pass, encryption) for the active SMTP plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_configure_provider(
    provider: str,
    api_key: str = None,
    username: str = None,
    password: str = None,
    region: str = None,
    from_email: str = None,
    from_name: str = None,
    plugin: str = "auto",
) -> dict:
    """Configure SMTP with preset settings for popular providers (Gmail, Outlook, SendGrid, Mailgun, Amazon SES, Postmark, Brevo)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/smtp", json=body)

@mcp.tool()
def smtp_test_send(
    to: str,
    subject: str = "WordPress SMTP Test Email",
    message: str = "This is a test email sent from your WordPress site to verify SMTP configuration.",
) -> dict:
    """Send a test email to verify SMTP configuration is working"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_get_failed_log(
    per_page: int = 20,
    page: int = 1,
    date_from: str = None,
    date_to: str = None,
) -> dict:
    """Get failed email log from the active SMTP plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_retry_failed(
    email_ids: list = None,
) -> dict:
    """Retry sending failed emails from the SMTP plugin log"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_get_sent_log(
    per_page: int = 20,
    page: int = 1,
    search: str = None,
    date_from: str = None,
    date_to: str = None,
) -> dict:
    """Get sent email log from the active SMTP plugin"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_check_spf_dkim(
    domain: str = None,
) -> dict:
    """Return SPF and DKIM configuration guidance for the current from-email domain"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_email_templates_list() -> dict:
    """List available WooCommerce and WordPress email templates"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def smtp_email_template_customize(
    template: str,
    enabled: bool = None,
    subject: str = None,
    heading: str = None,
    additional_content: str = None,
    header_image: str = None,
    base_color: str = None,
    background_color: str = None,
    body_background_color: str = None,
    text_color: str = None,
    footer_text: str = None,
) -> dict:
    """Customize a WooCommerce email template (header, footer, colors, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-mcp/v1/smtp", params=params)

@mcp.tool()
def speed_audit() -> dict:
    """Run a comprehensive speed audit on the WordPress site: check image sizes, lazy loading, caching, GZIP, minification, unused CSS/JS, render-blocking resources, and database health. Returns a score with categorized issues and fix recommendations."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_check_images(
    min_size_kb: int = None,
    min_width: int = None,
    per_page: int = None,
) -> dict:
    """Find images that are too large in file size or dimensions, hurting page load speed."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_compress_images(
    plugin: str = None,
    quality: str = None,
) -> dict:
    """Trigger image compression via an installed optimization plugin (Imagify, ShortPixel, Smush, EWWW)."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_convert_webp(
    plugin: str = None,
) -> dict:
    """Convert images to WebP format via installed plugin or get setup instructions."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_enable_lazy_load(
    images: bool = None,
    iframes: bool = None,
    videos: bool = None,
) -> dict:
    """Enable or verify lazy loading for images and iframes across the site."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def speed_check_caching() -> dict:
    """Verify that page caching is properly configured, checking all major caching plugins and server-level caching."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_configure_caching(
    plugin: str = None,
    page_cache: bool = None,
    browser_cache: bool = None,
    object_cache: bool = None,
    mobile_cache: bool = None,
) -> dict:
    """Auto-configure caching settings for WP Rocket, LiteSpeed Cache, W3 Total Cache, or WP Super Cache."""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def speed_check_gzip() -> dict:
    """Verify GZIP/Brotli compression is enabled on the server for text-based resources."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_enable_gzip(
    method: str = None,
) -> dict:
    """Enable GZIP compression via caching plugin settings or provide .htaccess/nginx rules."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def speed_check_minification() -> dict:
    """Check if CSS and JavaScript files are minified and concatenated."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_enable_minification(
    minify_css: bool = None,
    minify_js: bool = None,
    concatenate_css: bool = None,
    concatenate_js: bool = None,
) -> dict:
    """Enable CSS/JS minification and concatenation via caching or optimization plugin."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/settings", json=body)

@mcp.tool()
def speed_find_render_blocking(
    page_url: str = None,
) -> dict:
    """Identify render-blocking CSS and JavaScript resources that delay page rendering."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_defer_js(
    defer_all: bool = None,
    delay_js: bool = None,
    exclude: list = None,
) -> dict:
    """Configure JavaScript deferral/delay to eliminate render-blocking scripts."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_critical_css_generate(
    page_url: str = None,
) -> dict:
    """Generate critical above-the-fold CSS for faster initial rendering, or get instructions to set it up."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_remove_unused_css(
    enable: bool = None,
) -> dict:
    """Identify and remove or defer unused CSS to reduce page weight. Requires wp-mcp companion plugin."""
    body: dict = {}
    if enable is not None: body["enable"] = enable
    return _wp().post("/wp-mcp/v1/speed/unused-css", json=body)

@mcp.tool()
def speed_check_database() -> dict:
    """Check database health: table sizes, autoload size, orphaned data, post revisions, spam comments, transients."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_optimize_database(
    clean_revisions: bool = None,
    clean_drafts: bool = None,
    clean_spam: bool = None,
    clean_trash: bool = None,
    clean_transients: bool = None,
    optimize_tables: bool = None,
) -> dict:
    """Clean up the WordPress database: remove revisions, spam, transients, orphaned metadata, and optimize tables."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_check_hosting_response(
    urls: list = None,
) -> dict:
    """Check server Time To First Byte (TTFB) for the homepage and key pages."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_preload_key_requests(
    fonts: list = None,
    css: list = None,
    preconnect: list = None,
) -> dict:
    """Configure preloading for critical fonts, CSS, and other key resources."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def speed_get_recommendations() -> dict:
    """Get a prioritized list of speed improvements with estimated impact, effort, and step-by-step instructions."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def qa_check_page_status(
    page_id: int,
    post_type: str = "page",
) -> dict:
    """Verify a page loads without errors (checks HTTP status via REST)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_all_pages(
    post_type: str = "page",
    per_page: int = 100,
) -> dict:
    """Check all published pages for content issues (empty, missing title, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_broken_images(
    post_type: str = "page",
    per_page: int = 50,
) -> dict:
    """Find images in content that reference missing media IDs"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_missing_meta(
    post_type: str = "page",
    per_page: int = 100,
) -> dict:
    """Find pages missing SEO meta (title, description, OG image)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_missing_alt_text(
    per_page: int = 100,
) -> dict:
    """Find all media images without alt text"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_empty_pages(
    post_type: str = "page",
) -> dict:
    """Find published pages with no content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_draft_pages(
    post_type: str = "any",
    per_page: int = 50,
) -> dict:
    """List forgotten draft pages and posts"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_orphaned_pages() -> dict:
    """Find published pages not linked in any menu"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_broken_links(
    post_type: str = "page",
    per_page: int = 20,
) -> dict:
    """Scan post/page content for potentially broken internal links"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_check_heading_hierarchy(
    post_type: str = "page",
    per_page: int = 50,
) -> dict:
    """Check H1-H6 heading structure across pages for SEO issues"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_full_site_audit(
    include_posts: bool = True,
    include_products: bool = False,
) -> dict:
    """Run all QA checks and return comprehensive report"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def qa_generate_report(
    checks: list,
) -> dict:
    """Generate a formatted QA report with pass/fail/warning status for each check"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/pages", params=params)

@mcp.tool()
def webhooks_wc_list(
    per_page: int = 20,
    page: int = 1,
    status: str = None,
) -> dict:
    """List all WooCommerce webhooks"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_wc_create(
    name: str,
    topic: str,
    delivery_url: str,
    secret: str = None,
    status: str = "active",
    api_version: str = "wp_api_v3",
) -> dict:
    """Create a new WooCommerce webhook (fires HTTP POST on WC events)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wc/v3/webhooks", json=body)

@mcp.tool()
def webhooks_wc_update(
    id: int,
    name: str = None,
    topic: str = None,
    delivery_url: str = None,
    secret: str = None,
    status: str = None,
) -> dict:
    """Update an existing WooCommerce webhook"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().put(f"/wc/v3/webhooks/{id}", json=body)

@mcp.tool()
def webhooks_wc_delete(
    id: int,
) -> dict:
    """Delete a WooCommerce webhook"""
    params = {"force": True}
    return _wp().delete(f"/wc/v3/webhooks/{id}", params=params)

@mcp.tool()
def webhooks_wp_register(
    name: str,
    action: str,
    delivery_url: str,
    custom_action: str = None,
    secret: str = None,
    active: bool = True,
) -> dict:
    """Register a custom WordPress webhook that fires on WP action hooks (post_publish, user_register, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_wp_list(
    per_page: int = 20,
    page: int = 1,
) -> dict:
    """List registered WordPress webhooks (via WP Webhooks plugin or companion)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_wp_delete(
    id: int,
    webhook_group: str = None,
) -> dict:
    """Delete a registered WordPress webhook"""
    params = {}
    return _wp().delete(f"/wc/v3/webhooks/{id}", params=params)

@mcp.tool()
def webhooks_zapier_detect() -> dict:
    """Check if Zapier, WP Webhooks, or similar automation plugin is installed"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_zapier_triggers_list() -> dict:
    """List available Zapier triggers/actions (requires Zapier or WP Webhooks plugin)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_make_detect() -> dict:
    """Check if Make (Integromat) integration is connected or available"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_n8n_configure(
    webhook_url: str,
    events: list = None,
    secret: str = None,
    active: bool = True,
) -> dict:
    """Configure n8n webhook URL and settings for WordPress integration"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_test_send(
    delivery_url: str,
    topic: str = "test.ping",
    payload: dict = None,
) -> dict:
    """Send a test webhook payload to a delivery URL to verify connectivity"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_incoming_create(
    name: str,
    action: str,
    secret: str = None,
    response_format: str = "json",
) -> dict:
    """Create an incoming webhook endpoint on WordPress (receive data from external services)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wc/v3/webhooks", json=body)

@mcp.tool()
def webhooks_log_list(
    webhook_id: int = None,
    per_page: int = 20,
    page: int = 1,
    status: str = "all",
) -> dict:
    """View webhook delivery log (delivery attempts, response codes, timestamps)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def webhooks_retry_failed(
    webhook_id: int = None,
    delivery_id: int = None,
    retry_all_failed: bool = False,
) -> dict:
    """Retry failed webhook deliveries"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wc/v3/webhooks", params=params)

@mcp.tool()
def snippet_check_plugin() -> dict:
    """Detect which code snippet plugin is active: WPCode, Code Snippets, or none"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_list(
    per_page: int = 100,
    page: int = 1,
) -> dict:
    """List all code snippets (works with WPCode and Code Snippets plugin)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_get(
    id: int,
) -> dict:
    """Get a single snippet by ID with full code and metadata"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_create(
    title: str,
    code: str,
    type: str = None,
    active: bool = None,
    location: str = None,
    scope: str = None,
    priority: int = None,
    tags: list = None,
    description: str = None,
) -> dict:
    """Create a new code snippet (PHP, CSS, JS, HTML). Supports WPCode and Code Snippets plugin."""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_update(
    id: int,
    title: str = None,
    code: str = None,
    type: str = None,
    active: bool = None,
    location: str = None,
    priority: int = None,
    tags: list = None,
    description: str = None,
) -> dict:
    """Update an existing snippet: change code, title, status, or any property"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def snippet_delete(
    id: int,
) -> dict:
    """Permanently delete a code snippet by ID"""
    params = {}
    return _wp().delete(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def snippet_enable(
    id: int,
) -> dict:
    """Activate/enable a code snippet by ID"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_disable(
    id: int,
) -> dict:
    """Deactivate/disable a code snippet by ID (keeps code, stops execution)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_search(
    keyword: str,
    type: str = None,
    active_only: bool = None,
) -> dict:
    """Search snippets by keyword (matches title, code content, tags)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_bulk_toggle(
    ids: list,
    active: bool,
) -> dict:
    """Enable or disable multiple snippets by ID at once"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_clone(
    id: int,
    new_title: str = None,
) -> dict:
    """Clone/duplicate an existing snippet (creates inactive copy)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_create_php(
    title: str,
    code: str,
    scope: str = "global",
    priority: int = 10,
    active: bool = True,
    tags: list = None,
    description: str = None,
) -> dict:
    """Shorthand: create a PHP snippet — runs on every page load globally (or admin/frontend only)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_create_css(
    title: str,
    code: str,
    active: bool = True,
    tags: list = None,
    description: str = None,
) -> dict:
    """Shorthand: create a CSS snippet — injected into <head> on frontend pages"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_create_js(
    title: str,
    code: str,
    location: str = "body_end",
    active: bool = True,
    tags: list = None,
    description: str = None,
) -> dict:
    """Shorthand: create a JavaScript snippet — injected before </body> on frontend"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_create_html(
    title: str,
    code: str,
    location: str = "body_end",
    active: bool = True,
    tags: list = None,
    description: str = None,
) -> dict:
    """Shorthand: create an HTML snippet — inject HTML at header, footer, or specific hook"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_create_shortcode(
    shortcode_tag: str,
    output_html: str = None,
    php_callback: str = None,
    title: str = None,
    active: bool = True,
) -> dict:
    """Create a PHP snippet that registers a WordPress shortcode"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp-mcp/v1/dev", json=body)

@mcp.tool()
def snippet_create_action_hook(
    hook: str,
    php_code: str,
    priority: int = None,
    accepted_args: int = None,
    title: str = None,
    active: bool = True,
    scope: str = "global",
) -> dict:
    """Create a PHP snippet that hooks into a WordPress action (add_action)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_create_filter_hook(
    hook: str,
    php_code: str,
    priority: int = 10,
    accepted_args: int = 1,
    title: str = None,
    active: bool = True,
    scope: str = "global",
) -> dict:
    """Create a PHP snippet that hooks into a WordPress filter (add_filter)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def snippet_inject_header(
    title: str,
    code: str,
    active: bool = True,
) -> dict:
    """Inject arbitrary code into <head> site-wide (meta tags, tracking pixels, CSS, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_inject_footer(
    title: str,
    code: str,
    active: bool = True,
) -> dict:
    """Inject arbitrary code before </body> site-wide (analytics, chat widgets, JS, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_inject_via_options(
    location: str,
    code: str,
    mode: str = "append",
    option_key: str = None,
) -> dict:
    """FALLBACK: Inject code into header/footer via WordPress options (works without any snippet plugin). Uses wp_head / wp_footer hooks stored in options."""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def snippet_get_options_injection() -> dict:
    """Get the current code injected via snippet_inject_via_options (header and footer)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/settings", params=params)

@mcp.tool()
def snippet_wpcode_get_locations() -> dict:
    """Get all available WPCode snippet locations/positions (head_start, body_end, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_wpcode_set_location(
    id: int,
    location: str,
) -> dict:
    """Change where a WPCode snippet runs (location/position)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def snippet_export(
    ids: list = None,
) -> dict:
    """Export snippets as JSON (for backup or migration to another site)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def snippet_get_stats() -> dict:
    """Get summary stats: total snippets, active count, by type, by scope"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)
