"""WordPress seo tools -- generated by scripts/audit_wordpress_tools.py.

Do not edit by hand; re-run the script instead. Tools that failed the audit
are still emitted but listed in tool_registry._BROKEN_WORDPRESS_ACTIONS so
they are hidden from discovery.
"""
from __future__ import annotations

import base64 as base64_lib  # noqa: F401
import json  # noqa: F401
import mimetypes  # noqa: F401
import os  # noqa: F401
import re  # noqa: F401
from datetime import date, timedelta  # noqa: F401
from typing import Any, List, Optional  # noqa: F401
from urllib.parse import quote, urlparse  # noqa: F401

import requests  # noqa: F401

from mcp_instance import mcp
from permissions import require_editor  # noqa: F401

from .client import _trim, _unsupported_from_http, _wp  # noqa: F401
from ._helpers import *  # noqa: F401,F403 -- shared private helpers


@mcp.tool()
def aiseo_llmstxt_generate(
    post_types: list = None,
    per_page: int = 50,
    include_descriptions: bool = True,
) -> dict:
    """Generate /llms.txt content from site posts and pages (structured site summary for AI crawlers)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_llmstxt_get() -> dict:
    """Read current llms.txt content (if stored as a page or option)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_llmstxt_update(
    action: str,
    urls: list,
    titles: list = None,
    descriptions: list = None,
) -> dict:
    """Add or remove URLs from llms.txt content"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def aiseo_robots_txt_get() -> dict:
    """Read the current robots.txt content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_robots_txt_update(
    rules: list = None,
) -> dict:
    """Add AI bot rules to robots.txt (GPTBot, ClaudeBot, Google-Extended, CCBot, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def aiseo_topical_authority_map(
    post_type: str = "post",
    per_page: int = 100,
) -> dict:
    """Build a topical authority map / topic cluster from existing posts based on categories and keywords"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_topical_gap_analysis(
    category_id: int,
    per_page: int = 50,
) -> dict:
    """Find missing subtopics by analyzing existing content clusters and suggesting gaps"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_content_audit(
    id: int,
    type: str = "post",
) -> dict:
    """Audit content for AI-friendliness (clear structure, Q&A format, entity mentions, key takeaways)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_structured_answers_generate(
    id: int,
    type: str = "post",
) -> dict:
    """Generate Q&A blocks from post content for featured snippet / AI citation optimization"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_key_takeaways_generate(
    id: int,
    type: str = "post",
    max_points: int = 5,
) -> dict:
    """Extract key takeaway points from a post's content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_entity_extract(
    id: int,
    type: str = "post",
) -> dict:
    """Identify named entities (people, places, brands, concepts) mentioned in post content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_internal_linking_suggest(
    id: int,
    max_suggestions: int = 10,
    post_type: str = "post",
) -> dict:
    """Suggest internal links between posts based on content and keyword similarity"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_internal_linking_report(
    post_type: str = "post",
    per_page: int = 50,
) -> dict:
    """Report on internal linking: orphaned content, link distribution, posts with no inbound links"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_keyword_density_check(
    id: int,
    type: str = "post",
    keyword: str = None,
) -> dict:
    """Check keyword usage and density in a post's content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_readability_score(
    id: int,
    type: str = "post",
) -> dict:
    """Calculate readability score for a post (Flesch-Kincaid grade level, avg sentence/word length)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_content_length_audit(
    post_type: str = "post",
    min_words: int = 300,
    per_page: int = 50,
) -> dict:
    """Audit posts for minimum word count thresholds"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_heading_structure_audit(
    id: int,
    type: str = "post",
) -> dict:
    """Audit H1-H6 heading hierarchy in post content (missing H1, skipped levels, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aiseo_image_seo_audit(
    id: int,
    type: str = "post",
) -> dict:
    """Audit images in a post for SEO (missing alt text, filename quality, dimensions)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def redirects_detect_plugin() -> dict:
    """Detect which redirect plugin is active (Redirection, RankMath, Yoast Premium, SEOPress)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_list(
    per_page: int = 25,
    page: int = 1,
    filter_type: int = None,
) -> dict:
    """List all redirects (plugin-agnostic, auto-detects which plugin is active)"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if filter_type is not None: params["filter_type"] = filter_type
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_create(
    source: str,
    target: str,
    type: int = 301,
    match_type: str = "url",
    group_id: int = None,
) -> dict:
    """Create a redirect (plugin-agnostic)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def redirects_update(
    id: int,
    source: str = None,
    target: str = None,
    type: int = None,
    enabled: bool = None,
) -> dict:
    """Update an existing redirect"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/redirection/v1/redirect/{id}", json=body)

@mcp.tool()
def redirects_delete(
    id: int,
) -> dict:
    """Delete a redirect"""
    params = {}
    return _wp().delete(f"/redirection/v1/redirect/{id}", params=params)

@mcp.tool()
def redirects_bulk_import(
    redirects: list = 301,
) -> dict:
    """Import redirects in bulk from an array of redirect entries"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_export(
    format: str = "json",
) -> dict:
    """Export all redirects as a structured array"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_groups_list() -> dict:
    """List redirect groups (Redirection plugin)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_groups_create(
    name: str,
    module_id: int = 1,
) -> dict:
    """Create a redirect group (Redirection plugin)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def redirects_404_list(
    per_page: int = 25,
    page: int = 1,
    orderby: str = "total",
) -> dict:
    """List 404 errors / unmatched URLs"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_404_to_redirect(
    url: str,
    target: str,
    type: int = 301,
) -> dict:
    """Convert a 404 entry to a redirect"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_test(
    url: str,
) -> dict:
    """Test if a URL would be redirected (checks existing redirect rules)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_htaccess_add(
    source: str,
    target: str,
    type: int = 301,
    match_type: str = "exact",
) -> dict:
    """Generate an .htaccess redirect rule (for manual addition or companion plugin)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def redirects_htaccess_read() -> dict:
    """Read current .htaccess redirect rules (via companion endpoint)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def redirects_nginx_generate(
    per_page: int = 100,
) -> dict:
    """Generate Nginx redirect configuration from existing redirects"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def schema_set_for_post(
    id: int,
    schema: dict,
    type: str = "post",
) -> dict:
    """Inject JSON-LD schema markup into a post via post meta"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def schema_get_for_post(
    id: int,
    type: str = "post",
) -> dict:
    """Read existing JSON-LD schema from a post"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_remove_from_post(
    id: int,
    type: str = "post",
) -> dict:
    """Remove JSON-LD schema from a post"""
    params = {}
    return _wp().delete(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def schema_validate(
    schema: dict,
) -> dict:
    """Validate a JSON-LD schema object for basic correctness (required fields, @context, @type)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_article(
    id: int,
    article_type: str = "Article",
) -> dict:
    """Auto-generate Article/BlogPosting JSON-LD schema from a post's fields"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_product(
    id: int,
    include_reviews: bool = True,
) -> dict:
    """Auto-generate Product JSON-LD schema from a WooCommerce product"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_local_business(
    name: str,
    business_type: str = "LocalBusiness",
    address: dict = None,
    phone: str = None,
    email: str = None,
    url: str = None,
    image: str = None,
    geo: dict = None,
    opening_hours: list = None,
    price_range: str = None,
    post_id: int = None,
    post_type: str = "page",
) -> dict:
    """Generate LocalBusiness JSON-LD schema from site info"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_faq(
    questions: list = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate FAQPage JSON-LD schema from FAQ content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_howto(
    name: str,
    description: str = None,
    total_time: str = None,
    estimated_cost: dict = None,
    supply: list = None,
    tool: list = None,
    steps: list = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate HowTo JSON-LD schema from step-by-step content"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_recipe(
    name: str = None,
    description: str = None,
    image: str = None,
    author: str = None,
    prep_time: str = None,
    cook_time: str = None,
    total_time: str = None,
    servings: str = None,
    calories: str = None,
    category: str = None,
    cuisine: str = None,
    ingredients: list = None,
    instructions: list = None,
    rating_value: int = None,
    rating_count: int = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate Recipe JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_event(
    name: str,
    start_date: str,
    description: str = None,
    end_date: str = None,
    location_name: str = None,
    location_address: str = None,
    location_url: str = None,
    event_status: str = "EventScheduled",
    attendance_mode: str = "OfflineEventAttendanceMode",
    image: str = None,
    organizer: str = None,
    performer: str = None,
    price: str = None,
    currency: str = "USD",
    url: str = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate Event JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_breadcrumbs(
    items: list = None,
    post_id: int = None,
    post_type: str = "page",
) -> dict:
    """Generate BreadcrumbList JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_organization(
    name: str,
    url: str = None,
    logo: str = None,
    description: str = None,
    email: str = None,
    phone: str = None,
    address: dict = None,
    social_profiles: list = None,
    founding_date: str = None,
    founders: list = None,
    post_id: int = None,
    post_type: str = "page",
) -> dict:
    """Generate Organization JSON-LD schema with sameAs social profiles"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_video(
    name: str,
    description: str,
    thumbnail_url: str,
    upload_date: str,
    duration: str = None,
    content_url: str = None,
    embed_url: str = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate VideoObject JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_review(
    item_name: str,
    rating_value: int,
    item_type: str = "Product",
    review_body: str = None,
    author: str = None,
    best_rating: int = 5,
    aggregate: bool = False,
    review_count: int = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate Review or AggregateRating JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_job_posting(
    title: str,
    description: str,
    company_name: str,
    date_posted: str = None,
    valid_through: str = None,
    employment_type: str = "FULL_TIME",
    company_url: str = None,
    company_logo: str = None,
    location: str = None,
    remote: bool = False,
    salary_min: int = None,
    salary_max: int = None,
    salary_currency: str = "USD",
    salary_unit: str = "YEAR",
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate JobPosting JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_generate_real_estate(
    name: str,
    description: str = None,
    url: str = None,
    image: str = None,
    address: dict = None,
    price: int = None,
    currency: str = "USD",
    property_type: str = None,
    bedrooms: int = None,
    bathrooms: int = None,
    floor_size: str = None,
    lot_size: str = None,
    year_built: int = None,
    listing_agent: str = None,
    post_id: int = None,
    post_type: str = "post",
) -> dict:
    """Generate RealEstateListing JSON-LD schema"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_bulk_apply(
    schema_type: str,
    post_type: str = "post",
    per_page: int = 50,
    overwrite: bool = False,
) -> dict:
    """Apply a schema template to all posts of a specific type"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_audit_site(
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Audit which posts have or lack JSON-LD schema markup"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def schema_custom_jsonld(
    id: int,
    jsonld: str,
    type: str = "post",
) -> dict:
    """Inject raw custom JSON-LD markup into a post"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aioseo_meta_get(
    id: int,
    type: str = "post",
) -> dict:
    """Get AIOSEO meta for a post (_aioseo_title, _aioseo_description, _aioseo_keywords, _aioseo_robots, _aioseo_canonical_url, _aioseo_og_*, _aioseo_twitter_*)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def aioseo_meta_set(
    id: int,
    meta: dict,
    type: str = "post",
) -> dict:
    """Set AIOSEO meta fields for a post"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def aioseo_meta_bulk_set(
    updates: list,
) -> dict:
    """Set AIOSEO meta fields across many posts at once"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def aioseo_schema_set(
    id: int,
    schema_type: str,
    type: str = "post",
    schema_data: dict = None,
) -> dict:
    """Set AIOSEO schema markup type for a post"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def aioseo_redirects_list(
    per_page: int = 25,
    page: int = 1,
) -> dict:
    """List AIOSEO redirects"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def aioseo_redirects_create(
    from_val: str,
    to: str,
    type: int = 301,
) -> dict:
    """Create a redirect in AIOSEO"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def aioseo_sitemap_config(
    action: str = "get",
    settings: dict = None,
) -> dict:
    """Get or update AIOSEO sitemap settings"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def seopress_meta_get(
    id: int,
    type: str = "post",
) -> dict:
    """Get SEOPress meta for a post (_seopress_titles_title, _seopress_titles_desc, _seopress_robots_index, _seopress_social_fb_*, _seopress_social_twitter_*)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seopress_meta_set(
    id: int,
    meta: dict,
    type: str = "post",
) -> dict:
    """Set SEOPress meta fields for a post"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def seopress_redirects_list(
    per_page: int = 25,
    page: int = 1,
) -> dict:
    """List SEOPress redirects"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def seopress_redirects_create(
    from_val: str,
    to: str,
    type: int = 301,
) -> dict:
    """Create a redirect in SEOPress"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def seo_plugin_detect() -> dict:
    """Detect which SEO plugin is active on the site (Yoast, RankMath, AIOSEO, or SEOPress)"""
    params = {}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_meta_get_universal(
    id: int,
    type: str = "post",
) -> dict:
    """Get SEO meta for a post using whichever SEO plugin is active (auto-detects Yoast/RankMath/AIOSEO/SEOPress)"""
    params = {}
    if type is not None: params["type"] = type
    return _wp().get(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def seo_meta_set_universal(
    id: int,
    type: str = "post",
    title: str = None,
    description: str = None,
    focus_keyword: str = None,
    canonical: str = None,
    noindex: bool = None,
    og_title: str = None,
    og_description: str = None,
    og_image: str = None,
    twitter_title: str = None,
    twitter_description: str = None,
) -> dict:
    """Set SEO meta for a post using whichever SEO plugin is active (auto-detects). Accepts standard keys: title, description, focus_keyword, canonical, og_title, og_description, og_image, twitter_title, twitter_description, noindex"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def seo_migrate_meta(
    from_plugin: str,
    to_plugin: str,
    post_type: str = "post",
    per_page: int = 50,
    dry_run: bool = True,
) -> dict:
    """Migrate SEO meta from one plugin format to another (e.g. Yoast to RankMath) for all posts"""
    params = {}
    if from_plugin is not None: params["from_plugin"] = from_plugin
    if to_plugin is not None: params["to_plugin"] = to_plugin
    if per_page is not None: params["per_page"] = per_page
    if dry_run is not None: params["dry_run"] = dry_run
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_bulk_analyze(
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Analyze all posts for SEO completeness (title, description, focus keyword, OG data) across any SEO plugin"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_missing_meta_report(
    post_type: str = "post",
    per_page: int = 100,
    check: str = "all",
) -> dict:
    """Find posts missing SEO title, meta description, or focus keyword"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if check is not None: params["check"] = check
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_duplicate_meta_report(
    post_type: str = "post",
    per_page: int = 100,
    field: str = "both",
) -> dict:
    """Find posts with duplicate SEO titles or meta descriptions"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_keyword_cannibalization_check(
    post_type: str = "post",
    per_page: int = 100,
) -> dict:
    """Find posts targeting the same focus keyword (keyword cannibalization)"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_create_optimized_post(
    title: str,
    content: str,
    excerpt: str = None,
    slug: str = None,
    focus_keyword: str = None,
    seo_title: str = None,
    meta_description: str = None,
    categories: list = None,
    tags: list = None,
    featured_image_url: str = None,
    featured_image_alt: str = None,
    status: str = "publish",
    date: str = None,
    og_title: str = None,
    og_description: str = None,
    twitter_title: str = None,
    twitter_description: str = None,
    noindex: bool = None,
    canonical_url: str = None,
    schema_type: str = None,
    author_id: int = None,
    comment_status: str = "closed",
) -> dict:
    """Create a fully SEO-optimized blog post with Yoast meta, featured image URL, categories, tags, and canonical URL in one call"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_bulk_create_posts(
    posts: list = None,
) -> dict:
    """Create multiple SEO-optimized posts at once from an array of post data"""
    wp = _wp()
    results = []
    for post in (posts or []):
        body = post if isinstance(post, dict) else {"title": str(post)}
        try:
            results.append(wp.post("/wp/v2/posts", json=body))
        except Exception as exc:
            results.append({"error": str(exc)})
    return {"created": results, "count": len(results)}

@mcp.tool()
def seo_audit_posts(
    post_type: str = "post",
    per_page: int = 50,
    filter: str = "all",
) -> dict:
    """Audit SEO status of all posts — find posts with missing meta description, title, focus keyword, or low scores"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if filter is not None: params["filter"] = filter
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_fix_missing_meta(
    post_ids: list = None,
    post_type: str = "post",
    max_length: int = 155,
) -> dict:
    """For posts missing SEO meta description, auto-generate from excerpt or content"""
    params = {}
    if post_ids is not None: params["post_ids"] = post_ids
    if max_length is not None: params["max_length"] = max_length
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_update_all_og_images(
    post_type: str = "post",
    per_page: int = 50,
) -> dict:
    """Set Open Graph image for all posts that have a featured image but no OG image set"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_generate_sitemap_list(
    post_types: list = None,
    per_page: int = 100,
) -> dict:
    """Get a list of all public URLs on the site (for sitemap purposes)"""
    params = {}
    if post_types is not None: params["post_types"] = post_types
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def seo_internal_link_suggestions(
    post_id: int,
    focus_keyword: str = None,
    max_suggestions: int = 5,
) -> dict:
    """For a given post, find other posts that could be linked internally based on keyword overlap"""
    params = {}
    if focus_keyword is not None: params["focus_keyword"] = focus_keyword
    if max_suggestions is not None: params["max_suggestions"] = max_suggestions
    return _wp().get(f"/wp/v2/posts/{post_id}", params=params)

@mcp.tool()
def seo_create_category_page(
    name: str,
    slug: str = None,
    description: str = None,
    parent: int = None,
    seo_title: str = None,
    meta_description: str = None,
) -> dict:
    """Create a category with SEO-optimized description and settings"""
    body = {"name": name}
    if slug: body["slug"] = slug
    if description: body["description"] = description
    if parent: body["parent"] = parent
    return _wp().post("/wp/v2/categories", json=body)

@mcp.tool()
def seo_create_content_cluster(
    pillar_title: str = None,
    pillar_content: str = None,
    pillar_keyword: str = None,
    cluster_posts: list = None,
    category_id: int = None,
) -> dict:
    """Create a content cluster: pillar page + multiple supporting blog posts, all cross-linked"""
    wp = _wp()
    results = {}
    if pillar_title:
        pillar_body = {"title": pillar_title, "status": "draft"}
        if pillar_content: pillar_body["content"] = pillar_content
        if category_id: pillar_body["categories"] = [category_id]
        results["pillar"] = wp.post("/wp/v2/posts", json=pillar_body)
    results["cluster"] = []
    for post in (cluster_posts or []):
        body = post if isinstance(post, dict) else {"title": str(post)}
        if category_id and "categories" not in body: body["categories"] = [category_id]
        try:
            results["cluster"].append(wp.post("/wp/v2/posts", json=body))
        except Exception as exc:
            results["cluster"].append({"error": str(exc)})
    return results

@mcp.tool()
def seo_noindex_page(
    id: int,
    type: str = "page",
) -> dict:
    """Set a page/post to noindex (remove from search engines)"""
    params = {}
    if type is not None: params["type"] = type
    return _wp().get(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def seo_index_page(
    id: int,
    type: str = "page",
) -> dict:
    """Set a page/post to index (allow search engines)"""
    params = {}
    if type is not None: params["type"] = type
    return _wp().get(f"/wp/v2/posts/{id}", params=params)

@mcp.tool()
def seo_bulk_set_focus_keywords(
    updates: list = "post",
) -> dict:
    """Set focus keywords for multiple posts at once"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_get_all_focus_keywords(
    post_type: str = "post",
    per_page: int = 100,
    page: int = 1,
) -> dict:
    """Get focus keywords and SEO scores for all posts — useful for keyword gap analysis"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_update_schema_markup(
    id: int,
    schema_type: str,
    type: str = "post",
    schema_data: dict = None,
) -> dict:
    """Add schema markup to a post/page via meta field"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def rankmath_meta_get(
    id: int,
    type: str = "post",
) -> dict:
    """Get all RankMath SEO meta for a post (title, description, focus keyword, robots, canonical, OG, Twitter, schema, seo score, etc.)"""
    params = {}
    if type is not None: params["type"] = type
    return _wp().get(f"/rankmath/v1/{id}", params=params)

@mcp.tool()
def rankmath_meta_set(
    id: int,
    meta: dict,
    type: str = "post",
) -> dict:
    """Set any RankMath meta fields for a post via post meta update (rank_math_title, rank_math_description, rank_math_focus_keyword, rank_math_robots, rank_math_canonical_url, rank_math_og_*, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/rankmath/v1/{id}", json=body)

@mcp.tool()
def rankmath_meta_bulk_set(
    updates: list,
) -> dict:
    """Set RankMath meta fields across many posts at once"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/rankmath/v1", json=body)

@mcp.tool()
def rankmath_focus_keyword_set(
    id: int,
    keyword: str,
    type: str = "post",
) -> dict:
    """Set the RankMath focus keyword for a post"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/rankmath/v1/{id}", json=body)

@mcp.tool()
def rankmath_schema_type_set(
    id: int,
    schema_type: str,
    type: str = "post",
    schema_data: dict = None,
) -> dict:
    """Set the RankMath schema type for a post (Article, BlogPosting, Product, FAQ, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/rankmath/v1/{id}", json=body)

@mcp.tool()
def rankmath_options_get(
    option_key: str,
) -> dict:
    """Get RankMath plugin options (general settings, title settings, sitemap settings)"""
    params = {}
    if option_key is not None: params["option_key"] = option_key
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_options_set(
    option_key: str,
    values: dict,
) -> dict:
    """Update RankMath plugin options"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/rankmath/v1", json=body)

@mcp.tool()
def rankmath_modules_toggle(
    module: str,
    enable: bool,
) -> dict:
    """Enable or disable RankMath modules (sitemap, redirections, 404-monitor, schema, analytics, etc.)"""
    params = {}
    if module is not None: params["module"] = module
    if enable is not None: params["enable"] = enable
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_redirects_list(
    per_page: int = 25,
    page: int = 1,
) -> dict:
    """List all RankMath redirections"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_redirects_create(
    from_val: str,
    to: str,
    type: int = 301,
    status: str = "active",
) -> dict:
    """Create a redirect in RankMath"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/rankmath/v1", json=body)

@mcp.tool()
def rankmath_redirects_update(
    id: int,
    from_val: str = None,
    to: str = None,
    type: int = None,
    status: str = None,
) -> dict:
    """Update an existing RankMath redirect"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/rankmath/v1/{id}", json=body)

@mcp.tool()
def rankmath_redirects_delete(
    id: int,
) -> dict:
    """Delete a RankMath redirect"""
    params = {}
    return _wp().delete(f"/rankmath/v1/{id}", params=params)

@mcp.tool()
def rankmath_404_monitor_list(
    per_page: int = 25,
    page: int = 1,
    orderby: str = "times_accessed",
) -> dict:
    """List 404 errors tracked by RankMath 404 Monitor"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if orderby is not None: params["orderby"] = orderby
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_404_to_redirect(
    uri: str,
    to: str,
    type: int = 301,
) -> dict:
    """Convert a 404 entry to a redirect in RankMath"""
    params = {}
    if uri is not None: params["uri"] = uri
    if to is not None: params["to"] = to
    if type is not None: params["type"] = type
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_instant_index_url(
    url: str,
) -> dict:
    """Submit a URL for instant indexing via RankMath IndexNow"""
    params = {}
    if url is not None: params["url"] = url
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_sitemap_config(
    action: str = "get",
    settings: dict = None,
) -> dict:
    """Get or update RankMath sitemap configuration (post types, taxonomies, author sitemap, etc.)"""
    params = {}
    if action is not None: params["action"] = action
    if settings is not None: params["settings"] = settings
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_local_seo_configure(
    business_name: str = None,
    business_type: str = None,
    address: dict = None,
    phone: str = None,
    email: str = None,
    geo: dict = None,
    opening_hours: dict = None,
    price_range: str = None,
) -> dict:
    """Configure RankMath Local SEO settings (business name, address, phone, hours, geo, etc.)"""
    params = {}
    if business_name is not None: params["business_name"] = business_name
    if business_type is not None: params["business_type"] = business_type
    if address is not None: params["address"] = address
    if phone is not None: params["phone"] = phone
    if email is not None: params["email"] = email
    if geo is not None: params["geo"] = geo
    if opening_hours is not None: params["opening_hours"] = opening_hours
    if price_range is not None: params["price_range"] = price_range
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_title_template_set(
    content_type: str,
    template: str,
) -> dict:
    """Set RankMath title template for a post type or taxonomy (uses variables like %title%, %sitename%, %sep%)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/rankmath/v1", json=body)

@mcp.tool()
def rankmath_metadesc_template_set(
    content_type: str,
    template: str,
) -> dict:
    """Set RankMath meta description template for a post type or taxonomy"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/rankmath/v1", json=body)

@mcp.tool()
def rankmath_analytics_stats(
    period: str = "30days",
) -> dict:
    """Get RankMath Analytics/SEO statistics (search impressions, clicks, CTR, position)"""
    params = {}
    if period is not None: params["period"] = period
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_content_ai_generate(
    keyword: str,
    country: str = "us",
    language: str = "en",
) -> dict:
    """Use RankMath Content AI to generate SEO suggestions for a keyword"""
    params = {}
    if keyword is not None: params["keyword"] = keyword
    if country is not None: params["country"] = country
    if language is not None: params["language"] = language
    return _wp().get("/rankmath/v1", params=params)

@mcp.tool()
def rankmath_noindex_toggle(
    id: int,
    noindex: bool,
    type: str = "post",
) -> dict:
    """Toggle noindex for a post via RankMath robots meta"""
    params = {}
    if type is not None: params["type"] = type
    if noindex is not None: params["noindex"] = noindex
    return _wp().get(f"/rankmath/v1/{id}", params=params)

@mcp.tool()
def rankmath_primary_category_set(
    id: int,
    category_id: int,
) -> dict:
    """Set the primary category for a post in RankMath"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/rankmath/v1/{id}", json=body)

@mcp.tool()
def sitemap_detect_source() -> dict:
    """Detect which sitemap provider is active (Core WP, Yoast, RankMath, AIOSEO)"""
    params = {}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_get_url() -> dict:
    """Return the main sitemap URL for the site"""
    params = {}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_get_index() -> dict:
    """Fetch sitemap index entries (list of sub-sitemaps)"""
    params = {}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_submit_google(
    sitemap_url: str = None,
) -> dict:
    """Submit/ping sitemap to Google"""
    params = {}
    if sitemap_url is not None: params["sitemap_url"] = sitemap_url
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_submit_bing(
    sitemap_url: str = None,
    api_key: str = None,
) -> dict:
    """Submit sitemap to Bing via IndexNow API"""
    params = {}
    if sitemap_url is not None: params["sitemap_url"] = sitemap_url
    if api_key is not None: params["api_key"] = api_key
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_submit_all(
    sitemap_url: str = None,
    bing_api_key: str = None,
) -> dict:
    """Ping/submit sitemap to all major search engines (Google, Bing)"""
    params = {}
    if sitemap_url is not None: params["sitemap_url"] = sitemap_url
    if bing_api_key is not None: params["bing_api_key"] = bing_api_key
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_exclude_post(
    id: int,
    type: str = "post",
) -> dict:
    """Exclude a specific post from the sitemap (via noindex or plugin-specific setting)"""
    params = {}
    if type is not None: params["type"] = type
    return _wp().get(f"/wp-sitemap.xml/{id}", params=params)

@mcp.tool()
def sitemap_exclude_post_type(
    post_type: str,
) -> dict:
    """Exclude an entire post type from the sitemap"""
    params = {}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_include_custom_url(
    url: str,
    priority: int = 0.5,
    changefreq: str = "weekly",
) -> dict:
    """Add a custom URL to the sitemap (via plugin settings)"""
    params = {}
    if url is not None: params["url"] = url
    if priority is not None: params["priority"] = priority
    if changefreq is not None: params["changefreq"] = changefreq
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_image_config(
    enabled: bool,
) -> dict:
    """Enable or disable image sitemap (Yoast/RankMath)"""
    params = {}
    if enabled is not None: params["enabled"] = enabled
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_video_config(
    enabled: bool,
) -> dict:
    """Enable or disable video sitemap (Yoast/RankMath)"""
    params = {}
    if enabled is not None: params["enabled"] = enabled
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def sitemap_news_config(
    enabled: bool,
    publication_name: str = None,
    post_types: list = None,
) -> dict:
    """Configure news sitemap settings (Yoast News SEO / RankMath)"""
    params = {}
    if enabled is not None: params["enabled"] = enabled
    if publication_name is not None: params["publication_name"] = publication_name
    if post_types is not None: params["post_types"] = post_types
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def yoast_get_post_seo(
    id: int,
    type: str = "post",
) -> dict:
    """Get all Yoast SEO settings for a post or page (title, description, focus keyword, OG, schema, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def yoast_update_post_seo(
    id: int,
    type: str = "post",
    seo_title: str = None,
    meta_description: str = None,
    focus_keyword: str = None,
    canonical_url: str = None,
    og_title: str = None,
    og_description: str = None,
    og_image: str = None,
    twitter_title: str = None,
    twitter_description: str = None,
    twitter_image: str = None,
    noindex: bool = None,
    nofollow: bool = None,
    schema_type: str = None,
) -> dict:
    """Update Yoast SEO settings for a post/page — title, meta description, focus keyword, OG title/description, canonical URL, robots, etc."""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def yoast_bulk_update_seo(
    updates: list,
) -> dict:
    """Update SEO meta for multiple posts at once"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def yoast_get_term_seo(
    taxonomy: str,
    id: int,
) -> dict:
    """Get Yoast SEO settings for a category, tag, or custom term"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def yoast_update_term_seo(
    taxonomy: str,
    id: int,
    seo_title: str = None,
    meta_description: str = None,
    noindex: bool = None,
) -> dict:
    """Update Yoast SEO settings for a taxonomy term"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "id")}
    return _wp().post(f"/wp/v2/posts/{id}", json=body)

@mcp.tool()
def yoast_get_site_seo() -> dict:
    """Get site-wide Yoast SEO settings (site name, separator, social profiles, etc.)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def yoast_update_site_seo(
    website_name: str = None,
    title_separator: str = None,
    homepage_title: str = None,
    homepage_description: str = None,
    twitter_site: str = None,
    facebook_url: str = None,
    company_name: str = None,
    company_logo: str = None,
) -> dict:
    """Update site-wide Yoast SEO settings"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def yoast_create_redirect(
    from_val: str,
    to: str,
    type: int = 301,
) -> dict:
    """Create a 301/302 redirect using Yoast SEO Premium or Redirection plugin"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def yoast_get_redirects() -> dict:
    """List all Yoast redirects"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def yoast_analyze_content(
    id: int,
    type: str = "post",
) -> dict:
    """Get Yoast SEO readability and keyword analysis for a post (returns scores and suggestions)"""
    params = {k: v for k, v in locals().items() if v is not None}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def yoast_set_webmaster_codes(
    google_verification: str = None,
    bing_verification: str = None,
    yandex_verification: str = None,
    baidu_verification: str = None,
) -> dict:
    """Set Google Search Console, Bing, Yandex webmaster verification codes"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def yoast_get_all_posts_seo_scores(
    per_page: int = 50,
    page: int = 1,
    type: str = "post",
) -> dict:
    """Get SEO and readability scores for all posts (requires Yoast data in meta)"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if type is not None: params["type"] = type
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_set_post_meta_title(
    post_id: int,
    title: str,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta title for a post/page (works with Yoast, RankMath, AIOSEO, Slim SEO)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_post_meta_description(
    post_id: int,
    description: str,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta description for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_post_focus_keyword(
    post_id: int,
    keyword: str,
    plugin: str = "auto",
) -> dict:
    """Set the focus/primary keyword for a post (Yoast or RankMath)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_post_canonical(
    post_id: int,
    canonical_url: str,
    plugin: str = "auto",
) -> dict:
    """Set canonical URL for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_post_robots(
    post_id: int,
    noindex: bool = False,
    nofollow: bool = False,
    noarchive: bool = False,
    noimageindex: bool = False,
    plugin: str = "auto",
) -> dict:
    """Set robots meta directives for a post/page (noindex, nofollow, etc.)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_og_title(
    post_id: int,
    og_title: str,
    plugin: str = "auto",
) -> dict:
    """Set Open Graph title for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_og_description(
    post_id: int,
    og_description: str,
    plugin: str = "auto",
) -> dict:
    """Set Open Graph description for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_og_image(
    post_id: int,
    image_id: int = None,
    image_url: str = None,
    plugin: str = "auto",
) -> dict:
    """Set Open Graph (social share) image for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_twitter_card(
    post_id: int,
    twitter_title: str = None,
    twitter_description: str = None,
    twitter_image_id: int = None,
    twitter_card_type: str = "summary_large_image",
    plugin: str = "auto",
) -> dict:
    """Set Twitter Card meta for a post/page"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_set_tag_meta(
    tag_id: int,
    title: str = None,
    description: str = None,
    og_title: str = None,
    og_description: str = None,
    noindex: bool = None,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta title and description for a post tag"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_category_meta(
    category_id: int,
    title: str = None,
    description: str = None,
    og_title: str = None,
    og_description: str = None,
    noindex: bool = None,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta title and description for a category"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_custom_taxonomy_meta(
    taxonomy: str,
    term_id: int,
    title: str = None,
    description: str = None,
    noindex: bool = None,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta for any custom taxonomy term"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_get_taxonomy_seo(
    taxonomy: str,
    term_id: int,
) -> dict:
    """Get current SEO meta for a taxonomy term (category, tag, custom)"""
    params = {}
    if taxonomy is not None: params["taxonomy"] = taxonomy
    if term_id is not None: params["term_id"] = term_id
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_audit_posts_seo(
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
    check_focus_keyword: bool = True,
    check_og_image: bool = True,
) -> dict:
    """Audit all posts/pages for missing or weak SEO meta (title, description, focus keyword)"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if check_focus_keyword is not None: params["check_focus_keyword"] = check_focus_keyword
    if check_og_image is not None: params["check_og_image"] = check_og_image
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_get_posts_without_meta(
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Get all posts/pages missing SEO meta title or description"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_get_posts_without_focus_keyword(
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Get all posts/pages without a set focus keyword"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_find_duplicate_titles(
    post_type: str = "any",
) -> dict:
    """Find posts/pages with duplicate SEO meta titles"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_find_duplicate_descriptions(
    post_type: str = "any",
) -> dict:
    """Find posts/pages with duplicate meta descriptions"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_find_missing_alt_text(
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Find images in media library or posts missing alt text"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_find_thin_content(
    min_word_count: int = 300,
    post_type: str = "post",
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """Find posts/pages with thin content (below word count threshold)"""
    params = {}
    if min_word_count is not None: params["min_word_count"] = min_word_count
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_analyze_heading_structure(
    post_id: int,
) -> dict:
    """Analyze heading structure (H1, H2, H3...) for a post/page"""
    params = {}
    return _wp().get(f"/wp/v2/posts/{post_id}", params=params)

@mcp.tool()
def seo_bulk_set_meta_from_title(
    post_ids: list,
    title_pattern: str,
    plugin: str = "auto",
) -> dict:
    """Bulk generate and set SEO meta titles from post titles for multiple posts"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_bulk_noindex(
    post_ids: list,
    noindex: bool = True,
    plugin: str = "auto",
) -> dict:
    """Bulk set noindex on multiple posts/pages"""
    params = {}
    if post_ids is not None: params["post_ids"] = post_ids
    if noindex is not None: params["noindex"] = noindex
    if plugin is not None: params["plugin"] = plugin
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_add_faq_schema(
    post_id: int = None,
    faqs: list = None,
) -> dict:
    """Add FAQ schema markup to a post/page"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_add_howto_schema(
    post_id: int,
    name: str,
    steps: list,
    description: str = None,
    total_time: str = None,
    estimated_cost: str = None,
) -> dict:
    """Add HowTo schema markup to a post/page"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_add_article_schema(
    post_id: int,
    article_type: str = "BlogPosting",
    author_name: str = None,
    date_published: str = None,
    date_modified: str = None,
) -> dict:
    """Add Article/BlogPosting schema to a post"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_add_product_schema(
    post_id: int,
    product_name: str = None,
    description: str = None,
    sku: str = None,
    price: str = None,
    currency: str = "USD",
    availability: str = "InStock",
    brand: str = None,
    rating_value: int = None,
    review_count: int = None,
) -> dict:
    """Add Product schema to a post or WooCommerce product"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_add_review_schema(
    post_id: int,
    item_name: str,
    rating_value: int,
    item_type: str = None,
    best_rating: int = 5,
    worst_rating: int = 1,
    author: str = None,
    review_body: str = None,
    date_published: str = None,
) -> dict:
    """Add Review schema markup to a post/page"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wc/v3/products/reviews", json=body)

@mcp.tool()
def seo_add_local_business_schema(
    post_id: int,
    business_name: str,
    business_type: str = None,
    address_street: str = None,
    address_city: str = None,
    address_state: str = None,
    address_postal_code: str = None,
    address_country: str = None,
    telephone: str = None,
    opening_hours: list = None,
    geo_latitude: int = None,
    geo_longitude: int = None,
    price_range: str = None,
    image_url: str = None,
    website_url: str = None,
) -> dict:
    """Add LocalBusiness schema markup (great for local SEO)"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_add_event_schema(
    post_id: int,
    event_name: str,
    start_date: str,
    end_date: str = None,
    description: str = None,
    location_name: str = None,
    location_address: str = None,
    event_status: str = "EventScheduled",
    event_attendance_mode: str = None,
    image_url: str = None,
    organizer: str = None,
    price: str = None,
    currency: str = None,
) -> dict:
    """Add Event schema markup to a post/page"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/tribe/events/v1/events", json=body)

@mcp.tool()
def seo_create_301_redirect(
    from_url: str,
    to_url: str,
    plugin: str = "auto",
) -> dict:
    """Create a 301 permanent redirect"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def seo_create_302_redirect(
    from_url: str,
    to_url: str,
) -> dict:
    """Create a 302 temporary redirect"""
    body = {k: v for k, v in locals().items() if v is not None}
    return _wp().post("/redirection/v1/redirect", json=body)

@mcp.tool()
def seo_list_redirects(
    per_page: int = 50,
    page: int = 1,
    plugin: str = "auto",
) -> dict:
    """List all SEO redirects"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if plugin is not None: params["plugin"] = plugin
    return _wp().get("/redirection/v1/redirect", params=params)

@mcp.tool()
def seo_delete_redirect(
    id: int,
    plugin: str = "auto",
) -> dict:
    """Delete a redirect"""
    params = {}
    return _wp().delete(f"/redirection/v1/redirect/{id}", params=params)

@mcp.tool()
def seo_get_sitemap_url() -> dict:
    """Get the sitemap URL(s) for the site"""
    params = {}
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def seo_ping_sitemap_to_google(
    sitemap_url: str = None,
) -> dict:
    """Ping Google Search Console to re-index the sitemap"""
    params = {}
    if sitemap_url is not None: params["sitemap_url"] = sitemap_url
    return _wp().get("/wp-sitemap.xml", params=params)

@mcp.tool()
def seo_exclude_from_sitemap(
    post_id: int,
    exclude: bool = True,
    plugin: str = "auto",
) -> dict:
    """Exclude a post/page/term from the XML sitemap"""
    params = {}
    if exclude is not None: params["exclude"] = exclude
    if plugin is not None: params["plugin"] = plugin
    return _wp().get(f"/wp-sitemap.xml/{post_id}", params=params)

@mcp.tool()
def seo_get_all_noindex_pages(
    post_type: str = "any",
    per_page: int = 50,
) -> dict:
    """List all posts/pages currently set to noindex"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_check_canonical_issues(
    post_type: str = "post",
    per_page: int = 50,
) -> dict:
    """Find posts/pages with canonical URL issues (missing or pointing to wrong URL)"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_set_breadcrumbs_settings(
    enabled: bool = None,
    separator: str = "»",
    home_text: str = "Home",
    show_current: bool = True,
    show_category: bool = True,
    plugin: str = "auto",
) -> dict:
    """Configure breadcrumbs settings (SEO plugin)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_site_verification(
    google: str = None,
    bing: str = None,
    pinterest: str = None,
    yandex: str = None,
    baidu: str = None,
    plugin: str = "auto",
) -> dict:
    """Set site verification codes (Google, Bing, Pinterest, Yandex)"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_homepage_meta(
    title: str = None,
    description: str = None,
    og_title: str = None,
    og_description: str = None,
    og_image_id: int = None,
    plugin: str = "auto",
) -> dict:
    """Set SEO meta title and description for the homepage"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_archives_settings(
    author_archive_enabled: bool = None,
    author_archive_noindex: bool = None,
    date_archive_enabled: bool = None,
    date_archive_noindex: bool = None,
    search_noindex: bool = None,
    plugin: str = "auto",
) -> dict:
    """Configure SEO settings for author, date, and search archives"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_set_social_profiles(
    facebook_url: str = None,
    twitter_username: str = None,
    instagram_url: str = None,
    linkedin_url: str = None,
    youtube_url: str = None,
    pinterest_url: str = None,
    plugin: str = "auto",
) -> dict:
    """Set social media profile URLs for knowledge graph / SEO"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp-mcp/v1/social", json=body)

@mcp.tool()
def seo_set_organization_info(
    entity_type: str = "company",
    name: str = None,
    logo_id: int = None,
    description: str = None,
    same_as: list = None,
    plugin: str = "auto",
) -> dict:
    """Set organization/person info for SEO knowledge graph"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "name")}
    return _wp().post(f"/wp/v2/posts/{name}", json=body)

@mcp.tool()
def seo_get_blog_seo_overview(
    per_page: int = 50,
    page: int = 1,
    status: str = "publish",
) -> dict:
    """Get SEO overview for all blog posts: meta completeness, scores, keywords"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    if status is not None: params["status"] = status
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_update_post_slug(
    post_id: int,
    slug: str,
    auto_redirect: bool = True,
) -> dict:
    """Update the URL slug (permalink) of a post/page for SEO"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self", "post_id")}
    return _wp().post(f"/wp/v2/posts/{post_id}", json=body)

@mcp.tool()
def seo_get_robots_txt() -> dict:
    """Get the current robots.txt content"""
    params = {}
    return _wp().get("/wp/v2/posts", params=params)

@mcp.tool()
def seo_update_robots_txt(
    content: str,
    plugin: str = "auto",
) -> dict:
    """Update the robots.txt file content"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_inject_json_ld(
    post_id: int,
    json_ld: dict,
    plugin: str = "rankmath",
) -> dict:
    """Inject custom JSON-LD structured data into a post/page"""
    params = {}
    if json_ld is not None: params["json_ld"] = json_ld
    if plugin is not None: params["plugin"] = plugin
    return _wp().get(f"/wp/v2/posts/{post_id}", params=params)

@mcp.tool()
def seo_get_post_schema(
    post_id: int,
) -> dict:
    """Get the current structured data/schema for a post/page"""
    params = {}
    return _wp().get(f"/wp/v2/posts/{post_id}", params=params)

@mcp.tool()
def seo_set_image_alt(
    image_id: int,
    alt: str,
    title: str = None,
    caption: str = None,
    description: str = None,
) -> dict:
    """Set alt text for a media library image"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_bulk_set_image_alt(
    updates: list,
) -> dict:
    """Bulk set alt text for multiple images"""
    body = {k: v for k, v in locals().items() if v is not None and k not in ("self")}
    return _wp().post("/wp/v2/posts", json=body)

@mcp.tool()
def seo_list_images_without_alt(
    per_page: int = 50,
    page: int = 1,
) -> dict:
    """List all media library images missing alt text"""
    params = {}
    if per_page is not None: params["per_page"] = per_page
    if page is not None: params["page"] = page
    return _wp().get("/wp/v2/posts", params=params)
